/*
 * Survey Engine MVP API
 * Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ScoreResultCategoryScoresInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-10T10:06:02.786165952+06:00[Asia/Dhaka]", comments = "Generator version: 7.20.0")
public class ScoreResultCategoryScoresInner {
  public static final String SERIALIZED_NAME_CATEGORY_ID = "categoryId";
  @SerializedName(SERIALIZED_NAME_CATEGORY_ID)
  @javax.annotation.Nullable
  private UUID categoryId;

  public static final String SERIALIZED_NAME_RAW_SCORE = "rawScore";
  @SerializedName(SERIALIZED_NAME_RAW_SCORE)
  @javax.annotation.Nullable
  private BigDecimal rawScore;

  public static final String SERIALIZED_NAME_MAX_SCORE = "maxScore";
  @SerializedName(SERIALIZED_NAME_MAX_SCORE)
  @javax.annotation.Nullable
  private BigDecimal maxScore;

  public static final String SERIALIZED_NAME_NORMALIZED_SCORE = "normalizedScore";
  @SerializedName(SERIALIZED_NAME_NORMALIZED_SCORE)
  @javax.annotation.Nullable
  private BigDecimal normalizedScore;

  public static final String SERIALIZED_NAME_WEIGHT_PERCENTAGE = "weightPercentage";
  @SerializedName(SERIALIZED_NAME_WEIGHT_PERCENTAGE)
  @javax.annotation.Nullable
  private BigDecimal weightPercentage;

  public static final String SERIALIZED_NAME_WEIGHTED_SCORE = "weightedScore";
  @SerializedName(SERIALIZED_NAME_WEIGHTED_SCORE)
  @javax.annotation.Nullable
  private BigDecimal weightedScore;

  public ScoreResultCategoryScoresInner() {
  }

  public ScoreResultCategoryScoresInner categoryId(@javax.annotation.Nullable UUID categoryId) {
    this.categoryId = categoryId;
    return this;
  }

  /**
   * Get categoryId
   * @return categoryId
   */
  @javax.annotation.Nullable
  public UUID getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(@javax.annotation.Nullable UUID categoryId) {
    this.categoryId = categoryId;
  }


  public ScoreResultCategoryScoresInner rawScore(@javax.annotation.Nullable BigDecimal rawScore) {
    this.rawScore = rawScore;
    return this;
  }

  /**
   * Get rawScore
   * @return rawScore
   */
  @javax.annotation.Nullable
  public BigDecimal getRawScore() {
    return rawScore;
  }

  public void setRawScore(@javax.annotation.Nullable BigDecimal rawScore) {
    this.rawScore = rawScore;
  }


  public ScoreResultCategoryScoresInner maxScore(@javax.annotation.Nullable BigDecimal maxScore) {
    this.maxScore = maxScore;
    return this;
  }

  /**
   * Get maxScore
   * @return maxScore
   */
  @javax.annotation.Nullable
  public BigDecimal getMaxScore() {
    return maxScore;
  }

  public void setMaxScore(@javax.annotation.Nullable BigDecimal maxScore) {
    this.maxScore = maxScore;
  }


  public ScoreResultCategoryScoresInner normalizedScore(@javax.annotation.Nullable BigDecimal normalizedScore) {
    this.normalizedScore = normalizedScore;
    return this;
  }

  /**
   * Get normalizedScore
   * @return normalizedScore
   */
  @javax.annotation.Nullable
  public BigDecimal getNormalizedScore() {
    return normalizedScore;
  }

  public void setNormalizedScore(@javax.annotation.Nullable BigDecimal normalizedScore) {
    this.normalizedScore = normalizedScore;
  }


  public ScoreResultCategoryScoresInner weightPercentage(@javax.annotation.Nullable BigDecimal weightPercentage) {
    this.weightPercentage = weightPercentage;
    return this;
  }

  /**
   * Get weightPercentage
   * @return weightPercentage
   */
  @javax.annotation.Nullable
  public BigDecimal getWeightPercentage() {
    return weightPercentage;
  }

  public void setWeightPercentage(@javax.annotation.Nullable BigDecimal weightPercentage) {
    this.weightPercentage = weightPercentage;
  }


  public ScoreResultCategoryScoresInner weightedScore(@javax.annotation.Nullable BigDecimal weightedScore) {
    this.weightedScore = weightedScore;
    return this;
  }

  /**
   * Get weightedScore
   * @return weightedScore
   */
  @javax.annotation.Nullable
  public BigDecimal getWeightedScore() {
    return weightedScore;
  }

  public void setWeightedScore(@javax.annotation.Nullable BigDecimal weightedScore) {
    this.weightedScore = weightedScore;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ScoreResultCategoryScoresInner instance itself
   */
  public ScoreResultCategoryScoresInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScoreResultCategoryScoresInner scoreResultCategoryScoresInner = (ScoreResultCategoryScoresInner) o;
    return Objects.equals(this.categoryId, scoreResultCategoryScoresInner.categoryId) &&
        Objects.equals(this.rawScore, scoreResultCategoryScoresInner.rawScore) &&
        Objects.equals(this.maxScore, scoreResultCategoryScoresInner.maxScore) &&
        Objects.equals(this.normalizedScore, scoreResultCategoryScoresInner.normalizedScore) &&
        Objects.equals(this.weightPercentage, scoreResultCategoryScoresInner.weightPercentage) &&
        Objects.equals(this.weightedScore, scoreResultCategoryScoresInner.weightedScore)&&
        Objects.equals(this.additionalProperties, scoreResultCategoryScoresInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categoryId, rawScore, maxScore, normalizedScore, weightPercentage, weightedScore, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScoreResultCategoryScoresInner {\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    rawScore: ").append(toIndentedString(rawScore)).append("\n");
    sb.append("    maxScore: ").append(toIndentedString(maxScore)).append("\n");
    sb.append("    normalizedScore: ").append(toIndentedString(normalizedScore)).append("\n");
    sb.append("    weightPercentage: ").append(toIndentedString(weightPercentage)).append("\n");
    sb.append("    weightedScore: ").append(toIndentedString(weightedScore)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("categoryId", "rawScore", "maxScore", "normalizedScore", "weightPercentage", "weightedScore"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ScoreResultCategoryScoresInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ScoreResultCategoryScoresInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ScoreResultCategoryScoresInner is not found in the empty JSON string", ScoreResultCategoryScoresInner.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("categoryId") != null && !jsonObj.get("categoryId").isJsonNull()) && !jsonObj.get("categoryId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `categoryId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("categoryId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ScoreResultCategoryScoresInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ScoreResultCategoryScoresInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ScoreResultCategoryScoresInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ScoreResultCategoryScoresInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ScoreResultCategoryScoresInner>() {
           @Override
           public void write(JsonWriter out, ScoreResultCategoryScoresInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ScoreResultCategoryScoresInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             ScoreResultCategoryScoresInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ScoreResultCategoryScoresInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ScoreResultCategoryScoresInner
   * @throws IOException if the JSON string is invalid with respect to ScoreResultCategoryScoresInner
   */
  public static ScoreResultCategoryScoresInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ScoreResultCategoryScoresInner.class);
  }

  /**
   * Convert an instance of ScoreResultCategoryScoresInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

