/*
 * Survey Engine MVP API
 * Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.SurveyResponseResponseAnswersInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * SurveyResponseResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-09T15:26:32.980599292+06:00[Asia/Dhaka]", comments = "Generator version: 7.20.0")
public class SurveyResponseResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private UUID id;

  public static final String SERIALIZED_NAME_CAMPAIGN_ID = "campaignId";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_ID)
  @javax.annotation.Nullable
  private UUID campaignId;

  public static final String SERIALIZED_NAME_SURVEY_SNAPSHOT_ID = "surveySnapshotId";
  @SerializedName(SERIALIZED_NAME_SURVEY_SNAPSHOT_ID)
  @javax.annotation.Nullable
  private UUID surveySnapshotId;

  public static final String SERIALIZED_NAME_RESPONDENT_IDENTIFIER = "respondentIdentifier";
  @SerializedName(SERIALIZED_NAME_RESPONDENT_IDENTIFIER)
  @javax.annotation.Nullable
  private String respondentIdentifier;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    IN_PROGRESS("IN_PROGRESS"),
    
    SUBMITTED("SUBMITTED"),
    
    LOCKED("LOCKED"),
    
    REOPENED("REOPENED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String SERIALIZED_NAME_STARTED_AT = "startedAt";
  @SerializedName(SERIALIZED_NAME_STARTED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime startedAt;

  public static final String SERIALIZED_NAME_SUBMITTED_AT = "submittedAt";
  @SerializedName(SERIALIZED_NAME_SUBMITTED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime submittedAt;

  public static final String SERIALIZED_NAME_LOCKED_AT = "lockedAt";
  @SerializedName(SERIALIZED_NAME_LOCKED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime lockedAt;

  public static final String SERIALIZED_NAME_WEIGHT_PROFILE_ID = "weightProfileId";
  @SerializedName(SERIALIZED_NAME_WEIGHT_PROFILE_ID)
  @javax.annotation.Nullable
  private UUID weightProfileId;

  public static final String SERIALIZED_NAME_WEIGHTED_TOTAL_SCORE = "weightedTotalScore";
  @SerializedName(SERIALIZED_NAME_WEIGHTED_TOTAL_SCORE)
  @javax.annotation.Nullable
  private BigDecimal weightedTotalScore;

  public static final String SERIALIZED_NAME_SCORED_AT = "scoredAt";
  @SerializedName(SERIALIZED_NAME_SCORED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime scoredAt;

  public static final String SERIALIZED_NAME_ANSWERS = "answers";
  @SerializedName(SERIALIZED_NAME_ANSWERS)
  @javax.annotation.Nullable
  private List<SurveyResponseResponseAnswersInner> answers = new ArrayList<>();

  public SurveyResponseResponse() {
  }

  public SurveyResponseResponse id(@javax.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public UUID getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable UUID id) {
    this.id = id;
  }


  public SurveyResponseResponse campaignId(@javax.annotation.Nullable UUID campaignId) {
    this.campaignId = campaignId;
    return this;
  }

  /**
   * Get campaignId
   * @return campaignId
   */
  @javax.annotation.Nullable
  public UUID getCampaignId() {
    return campaignId;
  }

  public void setCampaignId(@javax.annotation.Nullable UUID campaignId) {
    this.campaignId = campaignId;
  }


  public SurveyResponseResponse surveySnapshotId(@javax.annotation.Nullable UUID surveySnapshotId) {
    this.surveySnapshotId = surveySnapshotId;
    return this;
  }

  /**
   * Get surveySnapshotId
   * @return surveySnapshotId
   */
  @javax.annotation.Nullable
  public UUID getSurveySnapshotId() {
    return surveySnapshotId;
  }

  public void setSurveySnapshotId(@javax.annotation.Nullable UUID surveySnapshotId) {
    this.surveySnapshotId = surveySnapshotId;
  }


  public SurveyResponseResponse respondentIdentifier(@javax.annotation.Nullable String respondentIdentifier) {
    this.respondentIdentifier = respondentIdentifier;
    return this;
  }

  /**
   * Get respondentIdentifier
   * @return respondentIdentifier
   */
  @javax.annotation.Nullable
  public String getRespondentIdentifier() {
    return respondentIdentifier;
  }

  public void setRespondentIdentifier(@javax.annotation.Nullable String respondentIdentifier) {
    this.respondentIdentifier = respondentIdentifier;
  }


  public SurveyResponseResponse status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public SurveyResponseResponse startedAt(@javax.annotation.Nullable OffsetDateTime startedAt) {
    this.startedAt = startedAt;
    return this;
  }

  /**
   * Get startedAt
   * @return startedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getStartedAt() {
    return startedAt;
  }

  public void setStartedAt(@javax.annotation.Nullable OffsetDateTime startedAt) {
    this.startedAt = startedAt;
  }


  public SurveyResponseResponse submittedAt(@javax.annotation.Nullable OffsetDateTime submittedAt) {
    this.submittedAt = submittedAt;
    return this;
  }

  /**
   * Get submittedAt
   * @return submittedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getSubmittedAt() {
    return submittedAt;
  }

  public void setSubmittedAt(@javax.annotation.Nullable OffsetDateTime submittedAt) {
    this.submittedAt = submittedAt;
  }


  public SurveyResponseResponse lockedAt(@javax.annotation.Nullable OffsetDateTime lockedAt) {
    this.lockedAt = lockedAt;
    return this;
  }

  /**
   * Get lockedAt
   * @return lockedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLockedAt() {
    return lockedAt;
  }

  public void setLockedAt(@javax.annotation.Nullable OffsetDateTime lockedAt) {
    this.lockedAt = lockedAt;
  }


  public SurveyResponseResponse weightProfileId(@javax.annotation.Nullable UUID weightProfileId) {
    this.weightProfileId = weightProfileId;
    return this;
  }

  /**
   * Get weightProfileId
   * @return weightProfileId
   */
  @javax.annotation.Nullable
  public UUID getWeightProfileId() {
    return weightProfileId;
  }

  public void setWeightProfileId(@javax.annotation.Nullable UUID weightProfileId) {
    this.weightProfileId = weightProfileId;
  }


  public SurveyResponseResponse weightedTotalScore(@javax.annotation.Nullable BigDecimal weightedTotalScore) {
    this.weightedTotalScore = weightedTotalScore;
    return this;
  }

  /**
   * Get weightedTotalScore
   * @return weightedTotalScore
   */
  @javax.annotation.Nullable
  public BigDecimal getWeightedTotalScore() {
    return weightedTotalScore;
  }

  public void setWeightedTotalScore(@javax.annotation.Nullable BigDecimal weightedTotalScore) {
    this.weightedTotalScore = weightedTotalScore;
  }


  public SurveyResponseResponse scoredAt(@javax.annotation.Nullable OffsetDateTime scoredAt) {
    this.scoredAt = scoredAt;
    return this;
  }

  /**
   * Get scoredAt
   * @return scoredAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getScoredAt() {
    return scoredAt;
  }

  public void setScoredAt(@javax.annotation.Nullable OffsetDateTime scoredAt) {
    this.scoredAt = scoredAt;
  }


  public SurveyResponseResponse answers(@javax.annotation.Nullable List<SurveyResponseResponseAnswersInner> answers) {
    this.answers = answers;
    return this;
  }

  public SurveyResponseResponse addAnswersItem(SurveyResponseResponseAnswersInner answersItem) {
    if (this.answers == null) {
      this.answers = new ArrayList<>();
    }
    this.answers.add(answersItem);
    return this;
  }

  /**
   * Get answers
   * @return answers
   */
  @javax.annotation.Nullable
  public List<SurveyResponseResponseAnswersInner> getAnswers() {
    return answers;
  }

  public void setAnswers(@javax.annotation.Nullable List<SurveyResponseResponseAnswersInner> answers) {
    this.answers = answers;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SurveyResponseResponse instance itself
   */
  public SurveyResponseResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SurveyResponseResponse surveyResponseResponse = (SurveyResponseResponse) o;
    return Objects.equals(this.id, surveyResponseResponse.id) &&
        Objects.equals(this.campaignId, surveyResponseResponse.campaignId) &&
        Objects.equals(this.surveySnapshotId, surveyResponseResponse.surveySnapshotId) &&
        Objects.equals(this.respondentIdentifier, surveyResponseResponse.respondentIdentifier) &&
        Objects.equals(this.status, surveyResponseResponse.status) &&
        Objects.equals(this.startedAt, surveyResponseResponse.startedAt) &&
        Objects.equals(this.submittedAt, surveyResponseResponse.submittedAt) &&
        Objects.equals(this.lockedAt, surveyResponseResponse.lockedAt) &&
        Objects.equals(this.weightProfileId, surveyResponseResponse.weightProfileId) &&
        Objects.equals(this.weightedTotalScore, surveyResponseResponse.weightedTotalScore) &&
        Objects.equals(this.scoredAt, surveyResponseResponse.scoredAt) &&
        Objects.equals(this.answers, surveyResponseResponse.answers)&&
        Objects.equals(this.additionalProperties, surveyResponseResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, campaignId, surveySnapshotId, respondentIdentifier, status, startedAt, submittedAt, lockedAt, weightProfileId, weightedTotalScore, scoredAt, answers, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SurveyResponseResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    campaignId: ").append(toIndentedString(campaignId)).append("\n");
    sb.append("    surveySnapshotId: ").append(toIndentedString(surveySnapshotId)).append("\n");
    sb.append("    respondentIdentifier: ").append(toIndentedString(respondentIdentifier)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    submittedAt: ").append(toIndentedString(submittedAt)).append("\n");
    sb.append("    lockedAt: ").append(toIndentedString(lockedAt)).append("\n");
    sb.append("    weightProfileId: ").append(toIndentedString(weightProfileId)).append("\n");
    sb.append("    weightedTotalScore: ").append(toIndentedString(weightedTotalScore)).append("\n");
    sb.append("    scoredAt: ").append(toIndentedString(scoredAt)).append("\n");
    sb.append("    answers: ").append(toIndentedString(answers)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "campaignId", "surveySnapshotId", "respondentIdentifier", "status", "startedAt", "submittedAt", "lockedAt", "weightProfileId", "weightedTotalScore", "scoredAt", "answers"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SurveyResponseResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SurveyResponseResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SurveyResponseResponse is not found in the empty JSON string", SurveyResponseResponse.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("campaignId") != null && !jsonObj.get("campaignId").isJsonNull()) && !jsonObj.get("campaignId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `campaignId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("campaignId").toString()));
      }
      if ((jsonObj.get("surveySnapshotId") != null && !jsonObj.get("surveySnapshotId").isJsonNull()) && !jsonObj.get("surveySnapshotId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `surveySnapshotId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("surveySnapshotId").toString()));
      }
      if ((jsonObj.get("respondentIdentifier") != null && !jsonObj.get("respondentIdentifier").isJsonNull()) && !jsonObj.get("respondentIdentifier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `respondentIdentifier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("respondentIdentifier").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("weightProfileId") != null && !jsonObj.get("weightProfileId").isJsonNull()) && !jsonObj.get("weightProfileId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `weightProfileId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("weightProfileId").toString()));
      }
      if (jsonObj.get("answers") != null && !jsonObj.get("answers").isJsonNull()) {
        JsonArray jsonArrayanswers = jsonObj.getAsJsonArray("answers");
        if (jsonArrayanswers != null) {
          // ensure the json data is an array
          if (!jsonObj.get("answers").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `answers` to be an array in the JSON string but got `%s`", jsonObj.get("answers").toString()));
          }

          // validate the optional field `answers` (array)
          for (int i = 0; i < jsonArrayanswers.size(); i++) {
            SurveyResponseResponseAnswersInner.validateJsonElement(jsonArrayanswers.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SurveyResponseResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SurveyResponseResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SurveyResponseResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SurveyResponseResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<SurveyResponseResponse>() {
           @Override
           public void write(JsonWriter out, SurveyResponseResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SurveyResponseResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             SurveyResponseResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SurveyResponseResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SurveyResponseResponse
   * @throws IOException if the JSON string is invalid with respect to SurveyResponseResponse
   */
  public static SurveyResponseResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SurveyResponseResponse.class);
  }

  /**
   * Convert an instance of SurveyResponseResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

