/* tslint:disable */
/* eslint-disable */
/**
 * Survey Engine MVP API
 * Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CampaignPreviewResponsePagesInnerQuestionsInner
 */
export interface CampaignPreviewResponsePagesInnerQuestionsInner {
    /**
     * 
     * @type {string}
     * @memberof CampaignPreviewResponsePagesInnerQuestionsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignPreviewResponsePagesInnerQuestionsInner
     */
    questionId?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignPreviewResponsePagesInnerQuestionsInner
     */
    questionVersionId?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignPreviewResponsePagesInnerQuestionsInner
     */
    categoryVersionId?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignPreviewResponsePagesInnerQuestionsInner
     */
    text?: string;
    /**
     * 
     * @type {CampaignPreviewResponsePagesInnerQuestionsInnerTypeEnum}
     * @memberof CampaignPreviewResponsePagesInnerQuestionsInner
     */
    type?: CampaignPreviewResponsePagesInnerQuestionsInnerTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof CampaignPreviewResponsePagesInnerQuestionsInner
     */
    maxScore?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CampaignPreviewResponsePagesInnerQuestionsInner
     */
    mandatory?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CampaignPreviewResponsePagesInnerQuestionsInner
     */
    sortOrder?: number;
    /**
     * 
     * @type {string}
     * @memberof CampaignPreviewResponsePagesInnerQuestionsInner
     */
    optionConfig?: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignPreviewResponsePagesInnerQuestionsInner
     */
    answerConfig?: string;
}


/**
 * @export
 */
export const CampaignPreviewResponsePagesInnerQuestionsInnerTypeEnum = {
    Rank: 'RANK',
    RatingScale: 'RATING_SCALE',
    SingleChoice: 'SINGLE_CHOICE',
    MultipleChoice: 'MULTIPLE_CHOICE'
} as const;
export type CampaignPreviewResponsePagesInnerQuestionsInnerTypeEnum = typeof CampaignPreviewResponsePagesInnerQuestionsInnerTypeEnum[keyof typeof CampaignPreviewResponsePagesInnerQuestionsInnerTypeEnum];


/**
 * Check if a given object implements the CampaignPreviewResponsePagesInnerQuestionsInner interface.
 */
export function instanceOfCampaignPreviewResponsePagesInnerQuestionsInner(value: object): value is CampaignPreviewResponsePagesInnerQuestionsInner {
    return true;
}

export function CampaignPreviewResponsePagesInnerQuestionsInnerFromJSON(json: any): CampaignPreviewResponsePagesInnerQuestionsInner {
    return CampaignPreviewResponsePagesInnerQuestionsInnerFromJSONTyped(json, false);
}

export function CampaignPreviewResponsePagesInnerQuestionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignPreviewResponsePagesInnerQuestionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'questionId': json['questionId'] == null ? undefined : json['questionId'],
        'questionVersionId': json['questionVersionId'] == null ? undefined : json['questionVersionId'],
        'categoryVersionId': json['categoryVersionId'] == null ? undefined : json['categoryVersionId'],
        'text': json['text'] == null ? undefined : json['text'],
        'type': json['type'] == null ? undefined : json['type'],
        'maxScore': json['maxScore'] == null ? undefined : json['maxScore'],
        'mandatory': json['mandatory'] == null ? undefined : json['mandatory'],
        'sortOrder': json['sortOrder'] == null ? undefined : json['sortOrder'],
        'optionConfig': json['optionConfig'] == null ? undefined : json['optionConfig'],
        'answerConfig': json['answerConfig'] == null ? undefined : json['answerConfig'],
    };
}

export function CampaignPreviewResponsePagesInnerQuestionsInnerToJSON(json: any): CampaignPreviewResponsePagesInnerQuestionsInner {
    return CampaignPreviewResponsePagesInnerQuestionsInnerToJSONTyped(json, false);
}

export function CampaignPreviewResponsePagesInnerQuestionsInnerToJSONTyped(value?: CampaignPreviewResponsePagesInnerQuestionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'questionId': value['questionId'],
        'questionVersionId': value['questionVersionId'],
        'categoryVersionId': value['categoryVersionId'],
        'text': value['text'],
        'type': value['type'],
        'maxScore': value['maxScore'],
        'mandatory': value['mandatory'],
        'sortOrder': value['sortOrder'],
        'optionConfig': value['optionConfig'],
        'answerConfig': value['answerConfig'],
    };
}

