/* tslint:disable */
/* eslint-disable */
/**
 * Survey Engine MVP API
 * Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeatureType } from './FeatureType';
import {
    FeatureTypeFromJSON,
    FeatureTypeFromJSONTyped,
    FeatureTypeToJSON,
    FeatureTypeToJSONTyped,
} from './FeatureType';
import type { FeatureCategory } from './FeatureCategory';
import {
    FeatureCategoryFromJSON,
    FeatureCategoryFromJSONTyped,
    FeatureCategoryToJSON,
    FeatureCategoryToJSONTyped,
} from './FeatureCategory';

/**
 * 
 * @export
 * @interface FeatureDefinitionDTO
 */
export interface FeatureDefinitionDTO {
    /**
     * 
     * @type {string}
     * @memberof FeatureDefinitionDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureDefinitionDTO
     */
    featureKey?: string;
    /**
     * 
     * @type {FeatureType}
     * @memberof FeatureDefinitionDTO
     */
    featureType?: FeatureType;
    /**
     * 
     * @type {FeatureCategory}
     * @memberof FeatureDefinitionDTO
     */
    category?: FeatureCategory;
    /**
     * 
     * @type {string}
     * @memberof FeatureDefinitionDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureDefinitionDTO
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FeatureDefinitionDTO
     */
    enabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof FeatureDefinitionDTO
     */
    rolloutPercentage?: number;
    /**
     * 
     * @type {string}
     * @memberof FeatureDefinitionDTO
     */
    minPlan?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FeatureDefinitionDTO
     */
    roles?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FeatureDefinitionDTO
     */
    platforms?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof FeatureDefinitionDTO
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof FeatureDefinitionDTO
     */
    createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof FeatureDefinitionDTO
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof FeatureDefinitionDTO
     */
    updatedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof FeatureDefinitionDTO
     */
    updatedAt?: Date;
}



/**
 * Check if a given object implements the FeatureDefinitionDTO interface.
 */
export function instanceOfFeatureDefinitionDTO(value: object): value is FeatureDefinitionDTO {
    return true;
}

export function FeatureDefinitionDTOFromJSON(json: any): FeatureDefinitionDTO {
    return FeatureDefinitionDTOFromJSONTyped(json, false);
}

export function FeatureDefinitionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureDefinitionDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'featureKey': json['featureKey'] == null ? undefined : json['featureKey'],
        'featureType': json['featureType'] == null ? undefined : FeatureTypeFromJSON(json['featureType']),
        'category': json['category'] == null ? undefined : FeatureCategoryFromJSON(json['category']),
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'rolloutPercentage': json['rolloutPercentage'] == null ? undefined : json['rolloutPercentage'],
        'minPlan': json['minPlan'] == null ? undefined : json['minPlan'],
        'roles': json['roles'] == null ? undefined : json['roles'],
        'platforms': json['platforms'] == null ? undefined : json['platforms'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function FeatureDefinitionDTOToJSON(json: any): FeatureDefinitionDTO {
    return FeatureDefinitionDTOToJSONTyped(json, false);
}

export function FeatureDefinitionDTOToJSONTyped(value?: FeatureDefinitionDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'featureKey': value['featureKey'],
        'featureType': FeatureTypeToJSON(value['featureType']),
        'category': FeatureCategoryToJSON(value['category']),
        'name': value['name'],
        'description': value['description'],
        'enabled': value['enabled'],
        'rolloutPercentage': value['rolloutPercentage'],
        'minPlan': value['minPlan'],
        'roles': value['roles'],
        'platforms': value['platforms'],
        'metadata': value['metadata'],
        'createdBy': value['createdBy'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedBy': value['updatedBy'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

