/* tslint:disable */
/* eslint-disable */
/**
 * Survey Engine MVP API
 * Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionResponse
 */
export interface QuestionResponse {
    /**
     * 
     * @type {string}
     * @memberof QuestionResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof QuestionResponse
     */
    text?: string;
    /**
     * 
     * @type {QuestionResponseTypeEnum}
     * @memberof QuestionResponse
     */
    type?: QuestionResponseTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof QuestionResponse
     */
    maxScore?: number;
    /**
     * 
     * @type {string}
     * @memberof QuestionResponse
     */
    optionConfig?: string;
    /**
     * 
     * @type {number}
     * @memberof QuestionResponse
     */
    currentVersion?: number;
    /**
     * 
     * @type {boolean}
     * @memberof QuestionResponse
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof QuestionResponse
     */
    createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof QuestionResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof QuestionResponse
     */
    updatedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof QuestionResponse
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const QuestionResponseTypeEnum = {
    Rank: 'RANK',
    RatingScale: 'RATING_SCALE',
    SingleChoice: 'SINGLE_CHOICE',
    MultipleChoice: 'MULTIPLE_CHOICE'
} as const;
export type QuestionResponseTypeEnum = typeof QuestionResponseTypeEnum[keyof typeof QuestionResponseTypeEnum];


/**
 * Check if a given object implements the QuestionResponse interface.
 */
export function instanceOfQuestionResponse(value: object): value is QuestionResponse {
    return true;
}

export function QuestionResponseFromJSON(json: any): QuestionResponse {
    return QuestionResponseFromJSONTyped(json, false);
}

export function QuestionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'text': json['text'] == null ? undefined : json['text'],
        'type': json['type'] == null ? undefined : json['type'],
        'maxScore': json['maxScore'] == null ? undefined : json['maxScore'],
        'optionConfig': json['optionConfig'] == null ? undefined : json['optionConfig'],
        'currentVersion': json['currentVersion'] == null ? undefined : json['currentVersion'],
        'active': json['active'] == null ? undefined : json['active'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function QuestionResponseToJSON(json: any): QuestionResponse {
    return QuestionResponseToJSONTyped(json, false);
}

export function QuestionResponseToJSONTyped(value?: QuestionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'],
        'type': value['type'],
        'maxScore': value['maxScore'],
        'optionConfig': value['optionConfig'],
        'currentVersion': value['currentVersion'],
        'active': value['active'],
        'createdBy': value['createdBy'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedBy': value['updatedBy'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

