/* tslint:disable */
/* eslint-disable */
/**
 * Survey Engine MVP API
 * Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseSubmissionRequestAnswersInner } from './ResponseSubmissionRequestAnswersInner';
import {
    ResponseSubmissionRequestAnswersInnerFromJSON,
    ResponseSubmissionRequestAnswersInnerFromJSONTyped,
    ResponseSubmissionRequestAnswersInnerToJSON,
    ResponseSubmissionRequestAnswersInnerToJSONTyped,
} from './ResponseSubmissionRequestAnswersInner';

/**
 * 
 * @export
 * @interface ResponseSubmissionRequest
 */
export interface ResponseSubmissionRequest {
    /**
     * 
     * @type {string}
     * @memberof ResponseSubmissionRequest
     */
    responseId?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseSubmissionRequest
     */
    campaignId: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseSubmissionRequest
     */
    respondentIdentifier?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseSubmissionRequest
     */
    respondentIp?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseSubmissionRequest
     */
    respondentDeviceFingerprint?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseSubmissionRequest
     */
    responderToken?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseSubmissionRequest
     */
    responderAccessCode?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ResponseSubmissionRequest
     */
    respondentMetadata?: { [key: string]: string; };
    /**
     * 
     * @type {Array<ResponseSubmissionRequestAnswersInner>}
     * @memberof ResponseSubmissionRequest
     */
    answers?: Array<ResponseSubmissionRequestAnswersInner>;
}

/**
 * Check if a given object implements the ResponseSubmissionRequest interface.
 */
export function instanceOfResponseSubmissionRequest(value: object): value is ResponseSubmissionRequest {
    if (!('campaignId' in value) || value['campaignId'] === undefined) return false;
    return true;
}

export function ResponseSubmissionRequestFromJSON(json: any): ResponseSubmissionRequest {
    return ResponseSubmissionRequestFromJSONTyped(json, false);
}

export function ResponseSubmissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseSubmissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'responseId': json['responseId'] == null ? undefined : json['responseId'],
        'campaignId': json['campaignId'],
        'respondentIdentifier': json['respondentIdentifier'] == null ? undefined : json['respondentIdentifier'],
        'respondentIp': json['respondentIp'] == null ? undefined : json['respondentIp'],
        'respondentDeviceFingerprint': json['respondentDeviceFingerprint'] == null ? undefined : json['respondentDeviceFingerprint'],
        'responderToken': json['responderToken'] == null ? undefined : json['responderToken'],
        'responderAccessCode': json['responderAccessCode'] == null ? undefined : json['responderAccessCode'],
        'respondentMetadata': json['respondentMetadata'] == null ? undefined : json['respondentMetadata'],
        'answers': json['answers'] == null ? undefined : ((json['answers'] as Array<any>).map(ResponseSubmissionRequestAnswersInnerFromJSON)),
    };
}

export function ResponseSubmissionRequestToJSON(json: any): ResponseSubmissionRequest {
    return ResponseSubmissionRequestToJSONTyped(json, false);
}

export function ResponseSubmissionRequestToJSONTyped(value?: ResponseSubmissionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'responseId': value['responseId'],
        'campaignId': value['campaignId'],
        'respondentIdentifier': value['respondentIdentifier'],
        'respondentIp': value['respondentIp'],
        'respondentDeviceFingerprint': value['respondentDeviceFingerprint'],
        'responderToken': value['responderToken'],
        'responderAccessCode': value['responderAccessCode'],
        'respondentMetadata': value['respondentMetadata'],
        'answers': value['answers'] == null ? undefined : ((value['answers'] as Array<any>).map(ResponseSubmissionRequestAnswersInnerToJSON)),
    };
}

