/* tslint:disable */
/* eslint-disable */
/**
 * Survey Engine MVP API
 * Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SurveyThemePalette
 */
export interface SurveyThemePalette {
    /**
     * 
     * @type {string}
     * @memberof SurveyThemePalette
     */
    background?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyThemePalette
     */
    shell?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyThemePalette
     */
    panel?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyThemePalette
     */
    card?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyThemePalette
     */
    border?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyThemePalette
     */
    textPrimary?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyThemePalette
     */
    textSecondary?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyThemePalette
     */
    primary?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyThemePalette
     */
    primaryText?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyThemePalette
     */
    accent?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyThemePalette
     */
    accentSoft?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyThemePalette
     */
    headerBackground?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyThemePalette
     */
    headerText?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyThemePalette
     */
    footerBackground?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyThemePalette
     */
    footerText?: string;
}

/**
 * Check if a given object implements the SurveyThemePalette interface.
 */
export function instanceOfSurveyThemePalette(value: object): value is SurveyThemePalette {
    return true;
}

export function SurveyThemePaletteFromJSON(json: any): SurveyThemePalette {
    return SurveyThemePaletteFromJSONTyped(json, false);
}

export function SurveyThemePaletteFromJSONTyped(json: any, ignoreDiscriminator: boolean): SurveyThemePalette {
    if (json == null) {
        return json;
    }
    return {
        
        'background': json['background'] == null ? undefined : json['background'],
        'shell': json['shell'] == null ? undefined : json['shell'],
        'panel': json['panel'] == null ? undefined : json['panel'],
        'card': json['card'] == null ? undefined : json['card'],
        'border': json['border'] == null ? undefined : json['border'],
        'textPrimary': json['textPrimary'] == null ? undefined : json['textPrimary'],
        'textSecondary': json['textSecondary'] == null ? undefined : json['textSecondary'],
        'primary': json['primary'] == null ? undefined : json['primary'],
        'primaryText': json['primaryText'] == null ? undefined : json['primaryText'],
        'accent': json['accent'] == null ? undefined : json['accent'],
        'accentSoft': json['accentSoft'] == null ? undefined : json['accentSoft'],
        'headerBackground': json['headerBackground'] == null ? undefined : json['headerBackground'],
        'headerText': json['headerText'] == null ? undefined : json['headerText'],
        'footerBackground': json['footerBackground'] == null ? undefined : json['footerBackground'],
        'footerText': json['footerText'] == null ? undefined : json['footerText'],
    };
}

export function SurveyThemePaletteToJSON(json: any): SurveyThemePalette {
    return SurveyThemePaletteToJSONTyped(json, false);
}

export function SurveyThemePaletteToJSONTyped(value?: SurveyThemePalette | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'background': value['background'],
        'shell': value['shell'],
        'panel': value['panel'],
        'card': value['card'],
        'border': value['border'],
        'textPrimary': value['textPrimary'],
        'textSecondary': value['textSecondary'],
        'primary': value['primary'],
        'primaryText': value['primaryText'],
        'accent': value['accent'],
        'accentSoft': value['accentSoft'],
        'headerBackground': value['headerBackground'],
        'headerText': value['headerText'],
        'footerBackground': value['footerBackground'],
        'footerText': value['footerText'],
    };
}

