/* tslint:disable */
/* eslint-disable */
/**
 * Survey Engine MVP API
 * Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlanDefinitionRequest
 */
export interface PlanDefinitionRequest {
    /**
     * 
     * @type {PlanDefinitionRequestPlanCodeEnum}
     * @memberof PlanDefinitionRequest
     */
    planCode: PlanDefinitionRequestPlanCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof PlanDefinitionRequest
     */
    displayName: string;
    /**
     * 
     * @type {number}
     * @memberof PlanDefinitionRequest
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof PlanDefinitionRequest
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof PlanDefinitionRequest
     */
    billingCycleDays: number;
    /**
     * 
     * @type {number}
     * @memberof PlanDefinitionRequest
     */
    trialDays: number;
    /**
     * 
     * @type {number}
     * @memberof PlanDefinitionRequest
     */
    maxCampaigns?: number;
    /**
     * 
     * @type {number}
     * @memberof PlanDefinitionRequest
     */
    maxResponsesPerCampaign?: number;
    /**
     * 
     * @type {number}
     * @memberof PlanDefinitionRequest
     */
    maxAdminUsers?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PlanDefinitionRequest
     */
    active?: boolean;
}


/**
 * @export
 */
export const PlanDefinitionRequestPlanCodeEnum = {
    Basic: 'BASIC',
    Pro: 'PRO',
    Enterprise: 'ENTERPRISE'
} as const;
export type PlanDefinitionRequestPlanCodeEnum = typeof PlanDefinitionRequestPlanCodeEnum[keyof typeof PlanDefinitionRequestPlanCodeEnum];


/**
 * Check if a given object implements the PlanDefinitionRequest interface.
 */
export function instanceOfPlanDefinitionRequest(value: object): value is PlanDefinitionRequest {
    if (!('planCode' in value) || value['planCode'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('billingCycleDays' in value) || value['billingCycleDays'] === undefined) return false;
    if (!('trialDays' in value) || value['trialDays'] === undefined) return false;
    return true;
}

export function PlanDefinitionRequestFromJSON(json: any): PlanDefinitionRequest {
    return PlanDefinitionRequestFromJSONTyped(json, false);
}

export function PlanDefinitionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanDefinitionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'planCode': json['planCode'],
        'displayName': json['displayName'],
        'price': json['price'],
        'currency': json['currency'],
        'billingCycleDays': json['billingCycleDays'],
        'trialDays': json['trialDays'],
        'maxCampaigns': json['maxCampaigns'] == null ? undefined : json['maxCampaigns'],
        'maxResponsesPerCampaign': json['maxResponsesPerCampaign'] == null ? undefined : json['maxResponsesPerCampaign'],
        'maxAdminUsers': json['maxAdminUsers'] == null ? undefined : json['maxAdminUsers'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function PlanDefinitionRequestToJSON(json: any): PlanDefinitionRequest {
    return PlanDefinitionRequestToJSONTyped(json, false);
}

export function PlanDefinitionRequestToJSONTyped(value?: PlanDefinitionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'planCode': value['planCode'],
        'displayName': value['displayName'],
        'price': value['price'],
        'currency': value['currency'],
        'billingCycleDays': value['billingCycleDays'],
        'trialDays': value['trialDays'],
        'maxCampaigns': value['maxCampaigns'],
        'maxResponsesPerCampaign': value['maxResponsesPerCampaign'],
        'maxAdminUsers': value['maxAdminUsers'],
        'active': value['active'],
    };
}

