/* tslint:disable */
/* eslint-disable */
/**
 * Survey Engine MVP API
 * Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SurveyResponsePagesInnerQuestionsInner
 */
export interface SurveyResponsePagesInnerQuestionsInner {
    /**
     * 
     * @type {string}
     * @memberof SurveyResponsePagesInnerQuestionsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyResponsePagesInnerQuestionsInner
     */
    questionId?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyResponsePagesInnerQuestionsInner
     */
    questionVersionId?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyResponsePagesInnerQuestionsInner
     */
    categoryId?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyResponsePagesInnerQuestionsInner
     */
    categoryVersionId?: string;
    /**
     * 
     * @type {number}
     * @memberof SurveyResponsePagesInnerQuestionsInner
     */
    categoryWeightPercentage?: number;
    /**
     * 
     * @type {number}
     * @memberof SurveyResponsePagesInnerQuestionsInner
     */
    sortOrder?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SurveyResponsePagesInnerQuestionsInner
     */
    mandatory?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SurveyResponsePagesInnerQuestionsInner
     */
    answerConfig?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyResponsePagesInnerQuestionsInner
     */
    pinnedQuestionText?: string;
    /**
     * 
     * @type {SurveyResponsePagesInnerQuestionsInnerPinnedQuestionTypeEnum}
     * @memberof SurveyResponsePagesInnerQuestionsInner
     */
    pinnedQuestionType?: SurveyResponsePagesInnerQuestionsInnerPinnedQuestionTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof SurveyResponsePagesInnerQuestionsInner
     */
    pinnedQuestionMaxScore?: number;
    /**
     * 
     * @type {string}
     * @memberof SurveyResponsePagesInnerQuestionsInner
     */
    pinnedQuestionOptionConfig?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyResponsePagesInnerQuestionsInner
     */
    pinnedCategoryName?: string;
    /**
     * 
     * @type {string}
     * @memberof SurveyResponsePagesInnerQuestionsInner
     */
    pinnedCategoryDescription?: string;
}


/**
 * @export
 */
export const SurveyResponsePagesInnerQuestionsInnerPinnedQuestionTypeEnum = {
    Rank: 'RANK',
    RatingScale: 'RATING_SCALE',
    SingleChoice: 'SINGLE_CHOICE',
    MultipleChoice: 'MULTIPLE_CHOICE'
} as const;
export type SurveyResponsePagesInnerQuestionsInnerPinnedQuestionTypeEnum = typeof SurveyResponsePagesInnerQuestionsInnerPinnedQuestionTypeEnum[keyof typeof SurveyResponsePagesInnerQuestionsInnerPinnedQuestionTypeEnum];


/**
 * Check if a given object implements the SurveyResponsePagesInnerQuestionsInner interface.
 */
export function instanceOfSurveyResponsePagesInnerQuestionsInner(value: object): value is SurveyResponsePagesInnerQuestionsInner {
    return true;
}

export function SurveyResponsePagesInnerQuestionsInnerFromJSON(json: any): SurveyResponsePagesInnerQuestionsInner {
    return SurveyResponsePagesInnerQuestionsInnerFromJSONTyped(json, false);
}

export function SurveyResponsePagesInnerQuestionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SurveyResponsePagesInnerQuestionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'questionId': json['questionId'] == null ? undefined : json['questionId'],
        'questionVersionId': json['questionVersionId'] == null ? undefined : json['questionVersionId'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'categoryVersionId': json['categoryVersionId'] == null ? undefined : json['categoryVersionId'],
        'categoryWeightPercentage': json['categoryWeightPercentage'] == null ? undefined : json['categoryWeightPercentage'],
        'sortOrder': json['sortOrder'] == null ? undefined : json['sortOrder'],
        'mandatory': json['mandatory'] == null ? undefined : json['mandatory'],
        'answerConfig': json['answerConfig'] == null ? undefined : json['answerConfig'],
        'pinnedQuestionText': json['pinnedQuestionText'] == null ? undefined : json['pinnedQuestionText'],
        'pinnedQuestionType': json['pinnedQuestionType'] == null ? undefined : json['pinnedQuestionType'],
        'pinnedQuestionMaxScore': json['pinnedQuestionMaxScore'] == null ? undefined : json['pinnedQuestionMaxScore'],
        'pinnedQuestionOptionConfig': json['pinnedQuestionOptionConfig'] == null ? undefined : json['pinnedQuestionOptionConfig'],
        'pinnedCategoryName': json['pinnedCategoryName'] == null ? undefined : json['pinnedCategoryName'],
        'pinnedCategoryDescription': json['pinnedCategoryDescription'] == null ? undefined : json['pinnedCategoryDescription'],
    };
}

export function SurveyResponsePagesInnerQuestionsInnerToJSON(json: any): SurveyResponsePagesInnerQuestionsInner {
    return SurveyResponsePagesInnerQuestionsInnerToJSONTyped(json, false);
}

export function SurveyResponsePagesInnerQuestionsInnerToJSONTyped(value?: SurveyResponsePagesInnerQuestionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'questionId': value['questionId'],
        'questionVersionId': value['questionVersionId'],
        'categoryId': value['categoryId'],
        'categoryVersionId': value['categoryVersionId'],
        'categoryWeightPercentage': value['categoryWeightPercentage'],
        'sortOrder': value['sortOrder'],
        'mandatory': value['mandatory'],
        'answerConfig': value['answerConfig'],
        'pinnedQuestionText': value['pinnedQuestionText'],
        'pinnedQuestionType': value['pinnedQuestionType'],
        'pinnedQuestionMaxScore': value['pinnedQuestionMaxScore'],
        'pinnedQuestionOptionConfig': value['pinnedQuestionOptionConfig'],
        'pinnedCategoryName': value['pinnedCategoryName'],
        'pinnedCategoryDescription': value['pinnedCategoryDescription'],
    };
}

