/*
Survey Engine MVP API

Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"time"
)


// AuditLogsAPIService AuditLogsAPI service
type AuditLogsAPIService service

type ApiGetPlatformAuditLogsRequest struct {
	ctx context.Context
	ApiService *AuditLogsAPIService
	page *int32
	size *int32
	action *string
	entityType *string
	tenantId *string
	actor *string
	from *time.Time
	to *time.Time
}

func (r ApiGetPlatformAuditLogsRequest) Page(page int32) ApiGetPlatformAuditLogsRequest {
	r.page = &page
	return r
}

func (r ApiGetPlatformAuditLogsRequest) Size(size int32) ApiGetPlatformAuditLogsRequest {
	r.size = &size
	return r
}

func (r ApiGetPlatformAuditLogsRequest) Action(action string) ApiGetPlatformAuditLogsRequest {
	r.action = &action
	return r
}

func (r ApiGetPlatformAuditLogsRequest) EntityType(entityType string) ApiGetPlatformAuditLogsRequest {
	r.entityType = &entityType
	return r
}

func (r ApiGetPlatformAuditLogsRequest) TenantId(tenantId string) ApiGetPlatformAuditLogsRequest {
	r.tenantId = &tenantId
	return r
}

func (r ApiGetPlatformAuditLogsRequest) Actor(actor string) ApiGetPlatformAuditLogsRequest {
	r.actor = &actor
	return r
}

func (r ApiGetPlatformAuditLogsRequest) From(from time.Time) ApiGetPlatformAuditLogsRequest {
	r.from = &from
	return r
}

func (r ApiGetPlatformAuditLogsRequest) To(to time.Time) ApiGetPlatformAuditLogsRequest {
	r.to = &to
	return r
}

func (r ApiGetPlatformAuditLogsRequest) Execute() (*PageAuditLogResponse, *http.Response, error) {
	return r.ApiService.GetPlatformAuditLogsExecute(r)
}

/*
GetPlatformAuditLogs Query platform-wide audit logs (SUPER_ADMIN)

Why this endpoint is needed:
Super-admin operations require cross-tenant traceability for investigations and compliance.

What this endpoint does:
It returns paged audit logs across all tenants with optional filters for actor/action/entity/tenant.

How this endpoint does it:
Controller applies optional filter predicates and queries audit repository with descending timestamp ordering.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetPlatformAuditLogsRequest
*/
func (a *AuditLogsAPIService) GetPlatformAuditLogs(ctx context.Context) ApiGetPlatformAuditLogsRequest {
	return ApiGetPlatformAuditLogsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return PageAuditLogResponse
func (a *AuditLogsAPIService) GetPlatformAuditLogsExecute(r ApiGetPlatformAuditLogsRequest) (*PageAuditLogResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PageAuditLogResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuditLogsAPIService.GetPlatformAuditLogs")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/admin/superadmin/audit-logs"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "form", "")
	} else {
		var defaultValue int32 = 0
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", defaultValue, "form", "")
		r.page = &defaultValue
	}
	if r.size != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "size", r.size, "form", "")
	} else {
		var defaultValue int32 = 20
		parameterAddToHeaderOrQuery(localVarQueryParams, "size", defaultValue, "form", "")
		r.size = &defaultValue
	}
	if r.action != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "action", r.action, "form", "")
	}
	if r.entityType != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "entityType", r.entityType, "form", "")
	}
	if r.tenantId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "tenantId", r.tenantId, "form", "")
	}
	if r.actor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "actor", r.actor, "form", "")
	}
	if r.from != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "from", r.from, "form", "")
	}
	if r.to != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "to", r.to, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetTenantAuditLogsRequest struct {
	ctx context.Context
	ApiService *AuditLogsAPIService
	page *int32
	size *int32
	action *string
	entityType *string
	from *time.Time
	to *time.Time
}

func (r ApiGetTenantAuditLogsRequest) Page(page int32) ApiGetTenantAuditLogsRequest {
	r.page = &page
	return r
}

func (r ApiGetTenantAuditLogsRequest) Size(size int32) ApiGetTenantAuditLogsRequest {
	r.size = &size
	return r
}

func (r ApiGetTenantAuditLogsRequest) Action(action string) ApiGetTenantAuditLogsRequest {
	r.action = &action
	return r
}

func (r ApiGetTenantAuditLogsRequest) EntityType(entityType string) ApiGetTenantAuditLogsRequest {
	r.entityType = &entityType
	return r
}

func (r ApiGetTenantAuditLogsRequest) From(from time.Time) ApiGetTenantAuditLogsRequest {
	r.from = &from
	return r
}

func (r ApiGetTenantAuditLogsRequest) To(to time.Time) ApiGetTenantAuditLogsRequest {
	r.to = &to
	return r
}

func (r ApiGetTenantAuditLogsRequest) Execute() (*PageAuditLogResponse, *http.Response, error) {
	return r.ApiService.GetTenantAuditLogsExecute(r)
}

/*
GetTenantAuditLogs Query tenant-scoped activity logs

Why this endpoint is needed:
Tenant operators need visibility into operational activity for troubleshooting and governance.

What this endpoint does:
It returns paged audit logs filtered to the current tenant context.

How this endpoint does it:
Controller derives tenant id from security context and applies optional filter parameters on audit-log repository.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetTenantAuditLogsRequest
*/
func (a *AuditLogsAPIService) GetTenantAuditLogs(ctx context.Context) ApiGetTenantAuditLogsRequest {
	return ApiGetTenantAuditLogsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return PageAuditLogResponse
func (a *AuditLogsAPIService) GetTenantAuditLogsExecute(r ApiGetTenantAuditLogsRequest) (*PageAuditLogResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PageAuditLogResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuditLogsAPIService.GetTenantAuditLogs")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/audit-logs"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "form", "")
	} else {
		var defaultValue int32 = 0
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", defaultValue, "form", "")
		r.page = &defaultValue
	}
	if r.size != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "size", r.size, "form", "")
	} else {
		var defaultValue int32 = 20
		parameterAddToHeaderOrQuery(localVarQueryParams, "size", defaultValue, "form", "")
		r.size = &defaultValue
	}
	if r.action != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "action", r.action, "form", "")
	}
	if r.entityType != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "entityType", r.entityType, "form", "")
	}
	if r.from != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "from", r.from, "form", "")
	}
	if r.to != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "to", r.to, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
