/*
Survey Engine MVP API

Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CampaignPreviewResponsePagesInnerCategoriesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignPreviewResponsePagesInnerCategoriesInner{}

// CampaignPreviewResponsePagesInnerCategoriesInner struct for CampaignPreviewResponsePagesInnerCategoriesInner
type CampaignPreviewResponsePagesInnerCategoriesInner struct {
	CategoryVersionId *string `json:"categoryVersionId,omitempty"`
	VersionNumber *int32 `json:"versionNumber,omitempty"`
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	WeightPercentage *float32 `json:"weightPercentage,omitempty"`
	SortOrder *int32 `json:"sortOrder,omitempty"`
	Questions []CampaignPreviewResponsePagesInnerCategoriesInnerQuestionsInner `json:"questions,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CampaignPreviewResponsePagesInnerCategoriesInner CampaignPreviewResponsePagesInnerCategoriesInner

// NewCampaignPreviewResponsePagesInnerCategoriesInner instantiates a new CampaignPreviewResponsePagesInnerCategoriesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignPreviewResponsePagesInnerCategoriesInner() *CampaignPreviewResponsePagesInnerCategoriesInner {
	this := CampaignPreviewResponsePagesInnerCategoriesInner{}
	return &this
}

// NewCampaignPreviewResponsePagesInnerCategoriesInnerWithDefaults instantiates a new CampaignPreviewResponsePagesInnerCategoriesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignPreviewResponsePagesInnerCategoriesInnerWithDefaults() *CampaignPreviewResponsePagesInnerCategoriesInner {
	this := CampaignPreviewResponsePagesInnerCategoriesInner{}
	return &this
}

// GetCategoryVersionId returns the CategoryVersionId field value if set, zero value otherwise.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) GetCategoryVersionId() string {
	if o == nil || IsNil(o.CategoryVersionId) {
		var ret string
		return ret
	}
	return *o.CategoryVersionId
}

// GetCategoryVersionIdOk returns a tuple with the CategoryVersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) GetCategoryVersionIdOk() (*string, bool) {
	if o == nil || IsNil(o.CategoryVersionId) {
		return nil, false
	}
	return o.CategoryVersionId, true
}

// HasCategoryVersionId returns a boolean if a field has been set.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) HasCategoryVersionId() bool {
	if o != nil && !IsNil(o.CategoryVersionId) {
		return true
	}

	return false
}

// SetCategoryVersionId gets a reference to the given string and assigns it to the CategoryVersionId field.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) SetCategoryVersionId(v string) {
	o.CategoryVersionId = &v
}

// GetVersionNumber returns the VersionNumber field value if set, zero value otherwise.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) GetVersionNumber() int32 {
	if o == nil || IsNil(o.VersionNumber) {
		var ret int32
		return ret
	}
	return *o.VersionNumber
}

// GetVersionNumberOk returns a tuple with the VersionNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) GetVersionNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.VersionNumber) {
		return nil, false
	}
	return o.VersionNumber, true
}

// HasVersionNumber returns a boolean if a field has been set.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) HasVersionNumber() bool {
	if o != nil && !IsNil(o.VersionNumber) {
		return true
	}

	return false
}

// SetVersionNumber gets a reference to the given int32 and assigns it to the VersionNumber field.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) SetVersionNumber(v int32) {
	o.VersionNumber = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) SetDescription(v string) {
	o.Description = &v
}

// GetWeightPercentage returns the WeightPercentage field value if set, zero value otherwise.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) GetWeightPercentage() float32 {
	if o == nil || IsNil(o.WeightPercentage) {
		var ret float32
		return ret
	}
	return *o.WeightPercentage
}

// GetWeightPercentageOk returns a tuple with the WeightPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) GetWeightPercentageOk() (*float32, bool) {
	if o == nil || IsNil(o.WeightPercentage) {
		return nil, false
	}
	return o.WeightPercentage, true
}

// HasWeightPercentage returns a boolean if a field has been set.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) HasWeightPercentage() bool {
	if o != nil && !IsNil(o.WeightPercentage) {
		return true
	}

	return false
}

// SetWeightPercentage gets a reference to the given float32 and assigns it to the WeightPercentage field.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) SetWeightPercentage(v float32) {
	o.WeightPercentage = &v
}

// GetSortOrder returns the SortOrder field value if set, zero value otherwise.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) GetSortOrder() int32 {
	if o == nil || IsNil(o.SortOrder) {
		var ret int32
		return ret
	}
	return *o.SortOrder
}

// GetSortOrderOk returns a tuple with the SortOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) GetSortOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.SortOrder) {
		return nil, false
	}
	return o.SortOrder, true
}

// HasSortOrder returns a boolean if a field has been set.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) HasSortOrder() bool {
	if o != nil && !IsNil(o.SortOrder) {
		return true
	}

	return false
}

// SetSortOrder gets a reference to the given int32 and assigns it to the SortOrder field.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) SetSortOrder(v int32) {
	o.SortOrder = &v
}

// GetQuestions returns the Questions field value if set, zero value otherwise.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) GetQuestions() []CampaignPreviewResponsePagesInnerCategoriesInnerQuestionsInner {
	if o == nil || IsNil(o.Questions) {
		var ret []CampaignPreviewResponsePagesInnerCategoriesInnerQuestionsInner
		return ret
	}
	return o.Questions
}

// GetQuestionsOk returns a tuple with the Questions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) GetQuestionsOk() ([]CampaignPreviewResponsePagesInnerCategoriesInnerQuestionsInner, bool) {
	if o == nil || IsNil(o.Questions) {
		return nil, false
	}
	return o.Questions, true
}

// HasQuestions returns a boolean if a field has been set.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) HasQuestions() bool {
	if o != nil && !IsNil(o.Questions) {
		return true
	}

	return false
}

// SetQuestions gets a reference to the given []CampaignPreviewResponsePagesInnerCategoriesInnerQuestionsInner and assigns it to the Questions field.
func (o *CampaignPreviewResponsePagesInnerCategoriesInner) SetQuestions(v []CampaignPreviewResponsePagesInnerCategoriesInnerQuestionsInner) {
	o.Questions = v
}

func (o CampaignPreviewResponsePagesInnerCategoriesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignPreviewResponsePagesInnerCategoriesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CategoryVersionId) {
		toSerialize["categoryVersionId"] = o.CategoryVersionId
	}
	if !IsNil(o.VersionNumber) {
		toSerialize["versionNumber"] = o.VersionNumber
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.WeightPercentage) {
		toSerialize["weightPercentage"] = o.WeightPercentage
	}
	if !IsNil(o.SortOrder) {
		toSerialize["sortOrder"] = o.SortOrder
	}
	if !IsNil(o.Questions) {
		toSerialize["questions"] = o.Questions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CampaignPreviewResponsePagesInnerCategoriesInner) UnmarshalJSON(data []byte) (err error) {
	varCampaignPreviewResponsePagesInnerCategoriesInner := _CampaignPreviewResponsePagesInnerCategoriesInner{}

	err = json.Unmarshal(data, &varCampaignPreviewResponsePagesInnerCategoriesInner)

	if err != nil {
		return err
	}

	*o = CampaignPreviewResponsePagesInnerCategoriesInner(varCampaignPreviewResponsePagesInnerCategoriesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "categoryVersionId")
		delete(additionalProperties, "versionNumber")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "weightPercentage")
		delete(additionalProperties, "sortOrder")
		delete(additionalProperties, "questions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCampaignPreviewResponsePagesInnerCategoriesInner struct {
	value *CampaignPreviewResponsePagesInnerCategoriesInner
	isSet bool
}

func (v NullableCampaignPreviewResponsePagesInnerCategoriesInner) Get() *CampaignPreviewResponsePagesInnerCategoriesInner {
	return v.value
}

func (v *NullableCampaignPreviewResponsePagesInnerCategoriesInner) Set(val *CampaignPreviewResponsePagesInnerCategoriesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignPreviewResponsePagesInnerCategoriesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignPreviewResponsePagesInnerCategoriesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignPreviewResponsePagesInnerCategoriesInner(val *CampaignPreviewResponsePagesInnerCategoriesInner) *NullableCampaignPreviewResponsePagesInnerCategoriesInner {
	return &NullableCampaignPreviewResponsePagesInnerCategoriesInner{value: val, isSet: true}
}

func (v NullableCampaignPreviewResponsePagesInnerCategoriesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignPreviewResponsePagesInnerCategoriesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


