/*
Survey Engine MVP API

Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SurveyThemeMotion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SurveyThemeMotion{}

// SurveyThemeMotion struct for SurveyThemeMotion
type SurveyThemeMotion struct {
	AnimationPreset *string `json:"animationPreset,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SurveyThemeMotion SurveyThemeMotion

// NewSurveyThemeMotion instantiates a new SurveyThemeMotion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSurveyThemeMotion() *SurveyThemeMotion {
	this := SurveyThemeMotion{}
	return &this
}

// NewSurveyThemeMotionWithDefaults instantiates a new SurveyThemeMotion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSurveyThemeMotionWithDefaults() *SurveyThemeMotion {
	this := SurveyThemeMotion{}
	return &this
}

// GetAnimationPreset returns the AnimationPreset field value if set, zero value otherwise.
func (o *SurveyThemeMotion) GetAnimationPreset() string {
	if o == nil || IsNil(o.AnimationPreset) {
		var ret string
		return ret
	}
	return *o.AnimationPreset
}

// GetAnimationPresetOk returns a tuple with the AnimationPreset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SurveyThemeMotion) GetAnimationPresetOk() (*string, bool) {
	if o == nil || IsNil(o.AnimationPreset) {
		return nil, false
	}
	return o.AnimationPreset, true
}

// HasAnimationPreset returns a boolean if a field has been set.
func (o *SurveyThemeMotion) HasAnimationPreset() bool {
	if o != nil && !IsNil(o.AnimationPreset) {
		return true
	}

	return false
}

// SetAnimationPreset gets a reference to the given string and assigns it to the AnimationPreset field.
func (o *SurveyThemeMotion) SetAnimationPreset(v string) {
	o.AnimationPreset = &v
}

func (o SurveyThemeMotion) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SurveyThemeMotion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AnimationPreset) {
		toSerialize["animationPreset"] = o.AnimationPreset
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SurveyThemeMotion) UnmarshalJSON(data []byte) (err error) {
	varSurveyThemeMotion := _SurveyThemeMotion{}

	err = json.Unmarshal(data, &varSurveyThemeMotion)

	if err != nil {
		return err
	}

	*o = SurveyThemeMotion(varSurveyThemeMotion)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "animationPreset")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSurveyThemeMotion struct {
	value *SurveyThemeMotion
	isSet bool
}

func (v NullableSurveyThemeMotion) Get() *SurveyThemeMotion {
	return v.value
}

func (v *NullableSurveyThemeMotion) Set(val *SurveyThemeMotion) {
	v.value = val
	v.isSet = true
}

func (v NullableSurveyThemeMotion) IsSet() bool {
	return v.isSet
}

func (v *NullableSurveyThemeMotion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSurveyThemeMotion(val *SurveyThemeMotion) *NullableSurveyThemeMotion {
	return &NullableSurveyThemeMotion{value: val, isSet: true}
}

func (v NullableSurveyThemeMotion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSurveyThemeMotion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


