/*
Survey Engine MVP API

Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the FeatureAnalyticsDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeatureAnalyticsDTO{}

// FeatureAnalyticsDTO struct for FeatureAnalyticsDTO
type FeatureAnalyticsDTO struct {
	FeatureKey *string `json:"featureKey,omitempty"`
	TotalUsers *int32 `json:"totalUsers,omitempty"`
	AccessedCount *int32 `json:"accessedCount,omitempty"`
	CompletedCount *int32 `json:"completedCount,omitempty"`
	CompletionRate *float64 `json:"completionRate,omitempty"`
	AverageAccessCount *float64 `json:"averageAccessCount,omitempty"`
	LastAccessedAt *time.Time `json:"lastAccessedAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FeatureAnalyticsDTO FeatureAnalyticsDTO

// NewFeatureAnalyticsDTO instantiates a new FeatureAnalyticsDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeatureAnalyticsDTO() *FeatureAnalyticsDTO {
	this := FeatureAnalyticsDTO{}
	return &this
}

// NewFeatureAnalyticsDTOWithDefaults instantiates a new FeatureAnalyticsDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeatureAnalyticsDTOWithDefaults() *FeatureAnalyticsDTO {
	this := FeatureAnalyticsDTO{}
	return &this
}

// GetFeatureKey returns the FeatureKey field value if set, zero value otherwise.
func (o *FeatureAnalyticsDTO) GetFeatureKey() string {
	if o == nil || IsNil(o.FeatureKey) {
		var ret string
		return ret
	}
	return *o.FeatureKey
}

// GetFeatureKeyOk returns a tuple with the FeatureKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureAnalyticsDTO) GetFeatureKeyOk() (*string, bool) {
	if o == nil || IsNil(o.FeatureKey) {
		return nil, false
	}
	return o.FeatureKey, true
}

// HasFeatureKey returns a boolean if a field has been set.
func (o *FeatureAnalyticsDTO) HasFeatureKey() bool {
	if o != nil && !IsNil(o.FeatureKey) {
		return true
	}

	return false
}

// SetFeatureKey gets a reference to the given string and assigns it to the FeatureKey field.
func (o *FeatureAnalyticsDTO) SetFeatureKey(v string) {
	o.FeatureKey = &v
}

// GetTotalUsers returns the TotalUsers field value if set, zero value otherwise.
func (o *FeatureAnalyticsDTO) GetTotalUsers() int32 {
	if o == nil || IsNil(o.TotalUsers) {
		var ret int32
		return ret
	}
	return *o.TotalUsers
}

// GetTotalUsersOk returns a tuple with the TotalUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureAnalyticsDTO) GetTotalUsersOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalUsers) {
		return nil, false
	}
	return o.TotalUsers, true
}

// HasTotalUsers returns a boolean if a field has been set.
func (o *FeatureAnalyticsDTO) HasTotalUsers() bool {
	if o != nil && !IsNil(o.TotalUsers) {
		return true
	}

	return false
}

// SetTotalUsers gets a reference to the given int32 and assigns it to the TotalUsers field.
func (o *FeatureAnalyticsDTO) SetTotalUsers(v int32) {
	o.TotalUsers = &v
}

// GetAccessedCount returns the AccessedCount field value if set, zero value otherwise.
func (o *FeatureAnalyticsDTO) GetAccessedCount() int32 {
	if o == nil || IsNil(o.AccessedCount) {
		var ret int32
		return ret
	}
	return *o.AccessedCount
}

// GetAccessedCountOk returns a tuple with the AccessedCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureAnalyticsDTO) GetAccessedCountOk() (*int32, bool) {
	if o == nil || IsNil(o.AccessedCount) {
		return nil, false
	}
	return o.AccessedCount, true
}

// HasAccessedCount returns a boolean if a field has been set.
func (o *FeatureAnalyticsDTO) HasAccessedCount() bool {
	if o != nil && !IsNil(o.AccessedCount) {
		return true
	}

	return false
}

// SetAccessedCount gets a reference to the given int32 and assigns it to the AccessedCount field.
func (o *FeatureAnalyticsDTO) SetAccessedCount(v int32) {
	o.AccessedCount = &v
}

// GetCompletedCount returns the CompletedCount field value if set, zero value otherwise.
func (o *FeatureAnalyticsDTO) GetCompletedCount() int32 {
	if o == nil || IsNil(o.CompletedCount) {
		var ret int32
		return ret
	}
	return *o.CompletedCount
}

// GetCompletedCountOk returns a tuple with the CompletedCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureAnalyticsDTO) GetCompletedCountOk() (*int32, bool) {
	if o == nil || IsNil(o.CompletedCount) {
		return nil, false
	}
	return o.CompletedCount, true
}

// HasCompletedCount returns a boolean if a field has been set.
func (o *FeatureAnalyticsDTO) HasCompletedCount() bool {
	if o != nil && !IsNil(o.CompletedCount) {
		return true
	}

	return false
}

// SetCompletedCount gets a reference to the given int32 and assigns it to the CompletedCount field.
func (o *FeatureAnalyticsDTO) SetCompletedCount(v int32) {
	o.CompletedCount = &v
}

// GetCompletionRate returns the CompletionRate field value if set, zero value otherwise.
func (o *FeatureAnalyticsDTO) GetCompletionRate() float64 {
	if o == nil || IsNil(o.CompletionRate) {
		var ret float64
		return ret
	}
	return *o.CompletionRate
}

// GetCompletionRateOk returns a tuple with the CompletionRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureAnalyticsDTO) GetCompletionRateOk() (*float64, bool) {
	if o == nil || IsNil(o.CompletionRate) {
		return nil, false
	}
	return o.CompletionRate, true
}

// HasCompletionRate returns a boolean if a field has been set.
func (o *FeatureAnalyticsDTO) HasCompletionRate() bool {
	if o != nil && !IsNil(o.CompletionRate) {
		return true
	}

	return false
}

// SetCompletionRate gets a reference to the given float64 and assigns it to the CompletionRate field.
func (o *FeatureAnalyticsDTO) SetCompletionRate(v float64) {
	o.CompletionRate = &v
}

// GetAverageAccessCount returns the AverageAccessCount field value if set, zero value otherwise.
func (o *FeatureAnalyticsDTO) GetAverageAccessCount() float64 {
	if o == nil || IsNil(o.AverageAccessCount) {
		var ret float64
		return ret
	}
	return *o.AverageAccessCount
}

// GetAverageAccessCountOk returns a tuple with the AverageAccessCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureAnalyticsDTO) GetAverageAccessCountOk() (*float64, bool) {
	if o == nil || IsNil(o.AverageAccessCount) {
		return nil, false
	}
	return o.AverageAccessCount, true
}

// HasAverageAccessCount returns a boolean if a field has been set.
func (o *FeatureAnalyticsDTO) HasAverageAccessCount() bool {
	if o != nil && !IsNil(o.AverageAccessCount) {
		return true
	}

	return false
}

// SetAverageAccessCount gets a reference to the given float64 and assigns it to the AverageAccessCount field.
func (o *FeatureAnalyticsDTO) SetAverageAccessCount(v float64) {
	o.AverageAccessCount = &v
}

// GetLastAccessedAt returns the LastAccessedAt field value if set, zero value otherwise.
func (o *FeatureAnalyticsDTO) GetLastAccessedAt() time.Time {
	if o == nil || IsNil(o.LastAccessedAt) {
		var ret time.Time
		return ret
	}
	return *o.LastAccessedAt
}

// GetLastAccessedAtOk returns a tuple with the LastAccessedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureAnalyticsDTO) GetLastAccessedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastAccessedAt) {
		return nil, false
	}
	return o.LastAccessedAt, true
}

// HasLastAccessedAt returns a boolean if a field has been set.
func (o *FeatureAnalyticsDTO) HasLastAccessedAt() bool {
	if o != nil && !IsNil(o.LastAccessedAt) {
		return true
	}

	return false
}

// SetLastAccessedAt gets a reference to the given time.Time and assigns it to the LastAccessedAt field.
func (o *FeatureAnalyticsDTO) SetLastAccessedAt(v time.Time) {
	o.LastAccessedAt = &v
}

func (o FeatureAnalyticsDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeatureAnalyticsDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FeatureKey) {
		toSerialize["featureKey"] = o.FeatureKey
	}
	if !IsNil(o.TotalUsers) {
		toSerialize["totalUsers"] = o.TotalUsers
	}
	if !IsNil(o.AccessedCount) {
		toSerialize["accessedCount"] = o.AccessedCount
	}
	if !IsNil(o.CompletedCount) {
		toSerialize["completedCount"] = o.CompletedCount
	}
	if !IsNil(o.CompletionRate) {
		toSerialize["completionRate"] = o.CompletionRate
	}
	if !IsNil(o.AverageAccessCount) {
		toSerialize["averageAccessCount"] = o.AverageAccessCount
	}
	if !IsNil(o.LastAccessedAt) {
		toSerialize["lastAccessedAt"] = o.LastAccessedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FeatureAnalyticsDTO) UnmarshalJSON(data []byte) (err error) {
	varFeatureAnalyticsDTO := _FeatureAnalyticsDTO{}

	err = json.Unmarshal(data, &varFeatureAnalyticsDTO)

	if err != nil {
		return err
	}

	*o = FeatureAnalyticsDTO(varFeatureAnalyticsDTO)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "featureKey")
		delete(additionalProperties, "totalUsers")
		delete(additionalProperties, "accessedCount")
		delete(additionalProperties, "completedCount")
		delete(additionalProperties, "completionRate")
		delete(additionalProperties, "averageAccessCount")
		delete(additionalProperties, "lastAccessedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFeatureAnalyticsDTO struct {
	value *FeatureAnalyticsDTO
	isSet bool
}

func (v NullableFeatureAnalyticsDTO) Get() *FeatureAnalyticsDTO {
	return v.value
}

func (v *NullableFeatureAnalyticsDTO) Set(val *FeatureAnalyticsDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureAnalyticsDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureAnalyticsDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureAnalyticsDTO(val *FeatureAnalyticsDTO) *NullableFeatureAnalyticsDTO {
	return &NullableFeatureAnalyticsDTO{value: val, isSet: true}
}

func (v NullableFeatureAnalyticsDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureAnalyticsDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


