/*
Survey Engine MVP API

Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CategoryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CategoryRequest{}

// CategoryRequest struct for CategoryRequest
type CategoryRequest struct {
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	QuestionMappings []CategoryQuestionMappingRequest `json:"questionMappings,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CategoryRequest CategoryRequest

// NewCategoryRequest instantiates a new CategoryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategoryRequest(name string) *CategoryRequest {
	this := CategoryRequest{}
	this.Name = name
	return &this
}

// NewCategoryRequestWithDefaults instantiates a new CategoryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryRequestWithDefaults() *CategoryRequest {
	this := CategoryRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CategoryRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CategoryRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CategoryRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CategoryRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CategoryRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CategoryRequest) SetDescription(v string) {
	o.Description = &v
}

// GetQuestionMappings returns the QuestionMappings field value if set, zero value otherwise.
func (o *CategoryRequest) GetQuestionMappings() []CategoryQuestionMappingRequest {
	if o == nil || IsNil(o.QuestionMappings) {
		var ret []CategoryQuestionMappingRequest
		return ret
	}
	return o.QuestionMappings
}

// GetQuestionMappingsOk returns a tuple with the QuestionMappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryRequest) GetQuestionMappingsOk() ([]CategoryQuestionMappingRequest, bool) {
	if o == nil || IsNil(o.QuestionMappings) {
		return nil, false
	}
	return o.QuestionMappings, true
}

// HasQuestionMappings returns a boolean if a field has been set.
func (o *CategoryRequest) HasQuestionMappings() bool {
	if o != nil && !IsNil(o.QuestionMappings) {
		return true
	}

	return false
}

// SetQuestionMappings gets a reference to the given []CategoryQuestionMappingRequest and assigns it to the QuestionMappings field.
func (o *CategoryRequest) SetQuestionMappings(v []CategoryQuestionMappingRequest) {
	o.QuestionMappings = v
}

func (o CategoryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CategoryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.QuestionMappings) {
		toSerialize["questionMappings"] = o.QuestionMappings
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CategoryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCategoryRequest := _CategoryRequest{}

	err = json.Unmarshal(data, &varCategoryRequest)

	if err != nil {
		return err
	}

	*o = CategoryRequest(varCategoryRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "questionMappings")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCategoryRequest struct {
	value *CategoryRequest
	isSet bool
}

func (v NullableCategoryRequest) Get() *CategoryRequest {
	return v.value
}

func (v *NullableCategoryRequest) Set(val *CategoryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryRequest(val *CategoryRequest) *NullableCategoryRequest {
	return &NullableCategoryRequest{value: val, isSet: true}
}

func (v NullableCategoryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


