/*
Survey Engine MVP API

Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ResponseSubmissionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseSubmissionRequest{}

// ResponseSubmissionRequest struct for ResponseSubmissionRequest
type ResponseSubmissionRequest struct {
	ResponseId *string `json:"responseId,omitempty"`
	CampaignId string `json:"campaignId"`
	RespondentIdentifier *string `json:"respondentIdentifier,omitempty"`
	RespondentIp *string `json:"respondentIp,omitempty"`
	RespondentDeviceFingerprint *string `json:"respondentDeviceFingerprint,omitempty"`
	ResponderToken *string `json:"responderToken,omitempty"`
	ResponderAccessCode *string `json:"responderAccessCode,omitempty"`
	RespondentMetadata map[string]string `json:"respondentMetadata,omitempty"`
	Answers []ResponseSubmissionRequestAnswersInner `json:"answers,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ResponseSubmissionRequest ResponseSubmissionRequest

// NewResponseSubmissionRequest instantiates a new ResponseSubmissionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseSubmissionRequest(campaignId string) *ResponseSubmissionRequest {
	this := ResponseSubmissionRequest{}
	this.CampaignId = campaignId
	return &this
}

// NewResponseSubmissionRequestWithDefaults instantiates a new ResponseSubmissionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseSubmissionRequestWithDefaults() *ResponseSubmissionRequest {
	this := ResponseSubmissionRequest{}
	return &this
}

// GetResponseId returns the ResponseId field value if set, zero value otherwise.
func (o *ResponseSubmissionRequest) GetResponseId() string {
	if o == nil || IsNil(o.ResponseId) {
		var ret string
		return ret
	}
	return *o.ResponseId
}

// GetResponseIdOk returns a tuple with the ResponseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseSubmissionRequest) GetResponseIdOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseId) {
		return nil, false
	}
	return o.ResponseId, true
}

// HasResponseId returns a boolean if a field has been set.
func (o *ResponseSubmissionRequest) HasResponseId() bool {
	if o != nil && !IsNil(o.ResponseId) {
		return true
	}

	return false
}

// SetResponseId gets a reference to the given string and assigns it to the ResponseId field.
func (o *ResponseSubmissionRequest) SetResponseId(v string) {
	o.ResponseId = &v
}

// GetCampaignId returns the CampaignId field value
func (o *ResponseSubmissionRequest) GetCampaignId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CampaignId
}

// GetCampaignIdOk returns a tuple with the CampaignId field value
// and a boolean to check if the value has been set.
func (o *ResponseSubmissionRequest) GetCampaignIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CampaignId, true
}

// SetCampaignId sets field value
func (o *ResponseSubmissionRequest) SetCampaignId(v string) {
	o.CampaignId = v
}

// GetRespondentIdentifier returns the RespondentIdentifier field value if set, zero value otherwise.
func (o *ResponseSubmissionRequest) GetRespondentIdentifier() string {
	if o == nil || IsNil(o.RespondentIdentifier) {
		var ret string
		return ret
	}
	return *o.RespondentIdentifier
}

// GetRespondentIdentifierOk returns a tuple with the RespondentIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseSubmissionRequest) GetRespondentIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.RespondentIdentifier) {
		return nil, false
	}
	return o.RespondentIdentifier, true
}

// HasRespondentIdentifier returns a boolean if a field has been set.
func (o *ResponseSubmissionRequest) HasRespondentIdentifier() bool {
	if o != nil && !IsNil(o.RespondentIdentifier) {
		return true
	}

	return false
}

// SetRespondentIdentifier gets a reference to the given string and assigns it to the RespondentIdentifier field.
func (o *ResponseSubmissionRequest) SetRespondentIdentifier(v string) {
	o.RespondentIdentifier = &v
}

// GetRespondentIp returns the RespondentIp field value if set, zero value otherwise.
func (o *ResponseSubmissionRequest) GetRespondentIp() string {
	if o == nil || IsNil(o.RespondentIp) {
		var ret string
		return ret
	}
	return *o.RespondentIp
}

// GetRespondentIpOk returns a tuple with the RespondentIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseSubmissionRequest) GetRespondentIpOk() (*string, bool) {
	if o == nil || IsNil(o.RespondentIp) {
		return nil, false
	}
	return o.RespondentIp, true
}

// HasRespondentIp returns a boolean if a field has been set.
func (o *ResponseSubmissionRequest) HasRespondentIp() bool {
	if o != nil && !IsNil(o.RespondentIp) {
		return true
	}

	return false
}

// SetRespondentIp gets a reference to the given string and assigns it to the RespondentIp field.
func (o *ResponseSubmissionRequest) SetRespondentIp(v string) {
	o.RespondentIp = &v
}

// GetRespondentDeviceFingerprint returns the RespondentDeviceFingerprint field value if set, zero value otherwise.
func (o *ResponseSubmissionRequest) GetRespondentDeviceFingerprint() string {
	if o == nil || IsNil(o.RespondentDeviceFingerprint) {
		var ret string
		return ret
	}
	return *o.RespondentDeviceFingerprint
}

// GetRespondentDeviceFingerprintOk returns a tuple with the RespondentDeviceFingerprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseSubmissionRequest) GetRespondentDeviceFingerprintOk() (*string, bool) {
	if o == nil || IsNil(o.RespondentDeviceFingerprint) {
		return nil, false
	}
	return o.RespondentDeviceFingerprint, true
}

// HasRespondentDeviceFingerprint returns a boolean if a field has been set.
func (o *ResponseSubmissionRequest) HasRespondentDeviceFingerprint() bool {
	if o != nil && !IsNil(o.RespondentDeviceFingerprint) {
		return true
	}

	return false
}

// SetRespondentDeviceFingerprint gets a reference to the given string and assigns it to the RespondentDeviceFingerprint field.
func (o *ResponseSubmissionRequest) SetRespondentDeviceFingerprint(v string) {
	o.RespondentDeviceFingerprint = &v
}

// GetResponderToken returns the ResponderToken field value if set, zero value otherwise.
func (o *ResponseSubmissionRequest) GetResponderToken() string {
	if o == nil || IsNil(o.ResponderToken) {
		var ret string
		return ret
	}
	return *o.ResponderToken
}

// GetResponderTokenOk returns a tuple with the ResponderToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseSubmissionRequest) GetResponderTokenOk() (*string, bool) {
	if o == nil || IsNil(o.ResponderToken) {
		return nil, false
	}
	return o.ResponderToken, true
}

// HasResponderToken returns a boolean if a field has been set.
func (o *ResponseSubmissionRequest) HasResponderToken() bool {
	if o != nil && !IsNil(o.ResponderToken) {
		return true
	}

	return false
}

// SetResponderToken gets a reference to the given string and assigns it to the ResponderToken field.
func (o *ResponseSubmissionRequest) SetResponderToken(v string) {
	o.ResponderToken = &v
}

// GetResponderAccessCode returns the ResponderAccessCode field value if set, zero value otherwise.
func (o *ResponseSubmissionRequest) GetResponderAccessCode() string {
	if o == nil || IsNil(o.ResponderAccessCode) {
		var ret string
		return ret
	}
	return *o.ResponderAccessCode
}

// GetResponderAccessCodeOk returns a tuple with the ResponderAccessCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseSubmissionRequest) GetResponderAccessCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ResponderAccessCode) {
		return nil, false
	}
	return o.ResponderAccessCode, true
}

// HasResponderAccessCode returns a boolean if a field has been set.
func (o *ResponseSubmissionRequest) HasResponderAccessCode() bool {
	if o != nil && !IsNil(o.ResponderAccessCode) {
		return true
	}

	return false
}

// SetResponderAccessCode gets a reference to the given string and assigns it to the ResponderAccessCode field.
func (o *ResponseSubmissionRequest) SetResponderAccessCode(v string) {
	o.ResponderAccessCode = &v
}

// GetRespondentMetadata returns the RespondentMetadata field value if set, zero value otherwise.
func (o *ResponseSubmissionRequest) GetRespondentMetadata() map[string]string {
	if o == nil || IsNil(o.RespondentMetadata) {
		var ret map[string]string
		return ret
	}
	return o.RespondentMetadata
}

// GetRespondentMetadataOk returns a tuple with the RespondentMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseSubmissionRequest) GetRespondentMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.RespondentMetadata) {
		return map[string]string{}, false
	}
	return o.RespondentMetadata, true
}

// HasRespondentMetadata returns a boolean if a field has been set.
func (o *ResponseSubmissionRequest) HasRespondentMetadata() bool {
	if o != nil && !IsNil(o.RespondentMetadata) {
		return true
	}

	return false
}

// SetRespondentMetadata gets a reference to the given map[string]string and assigns it to the RespondentMetadata field.
func (o *ResponseSubmissionRequest) SetRespondentMetadata(v map[string]string) {
	o.RespondentMetadata = v
}

// GetAnswers returns the Answers field value if set, zero value otherwise.
func (o *ResponseSubmissionRequest) GetAnswers() []ResponseSubmissionRequestAnswersInner {
	if o == nil || IsNil(o.Answers) {
		var ret []ResponseSubmissionRequestAnswersInner
		return ret
	}
	return o.Answers
}

// GetAnswersOk returns a tuple with the Answers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseSubmissionRequest) GetAnswersOk() ([]ResponseSubmissionRequestAnswersInner, bool) {
	if o == nil || IsNil(o.Answers) {
		return nil, false
	}
	return o.Answers, true
}

// HasAnswers returns a boolean if a field has been set.
func (o *ResponseSubmissionRequest) HasAnswers() bool {
	if o != nil && !IsNil(o.Answers) {
		return true
	}

	return false
}

// SetAnswers gets a reference to the given []ResponseSubmissionRequestAnswersInner and assigns it to the Answers field.
func (o *ResponseSubmissionRequest) SetAnswers(v []ResponseSubmissionRequestAnswersInner) {
	o.Answers = v
}

func (o ResponseSubmissionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseSubmissionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ResponseId) {
		toSerialize["responseId"] = o.ResponseId
	}
	toSerialize["campaignId"] = o.CampaignId
	if !IsNil(o.RespondentIdentifier) {
		toSerialize["respondentIdentifier"] = o.RespondentIdentifier
	}
	if !IsNil(o.RespondentIp) {
		toSerialize["respondentIp"] = o.RespondentIp
	}
	if !IsNil(o.RespondentDeviceFingerprint) {
		toSerialize["respondentDeviceFingerprint"] = o.RespondentDeviceFingerprint
	}
	if !IsNil(o.ResponderToken) {
		toSerialize["responderToken"] = o.ResponderToken
	}
	if !IsNil(o.ResponderAccessCode) {
		toSerialize["responderAccessCode"] = o.ResponderAccessCode
	}
	if !IsNil(o.RespondentMetadata) {
		toSerialize["respondentMetadata"] = o.RespondentMetadata
	}
	if !IsNil(o.Answers) {
		toSerialize["answers"] = o.Answers
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResponseSubmissionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"campaignId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseSubmissionRequest := _ResponseSubmissionRequest{}

	err = json.Unmarshal(data, &varResponseSubmissionRequest)

	if err != nil {
		return err
	}

	*o = ResponseSubmissionRequest(varResponseSubmissionRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "responseId")
		delete(additionalProperties, "campaignId")
		delete(additionalProperties, "respondentIdentifier")
		delete(additionalProperties, "respondentIp")
		delete(additionalProperties, "respondentDeviceFingerprint")
		delete(additionalProperties, "responderToken")
		delete(additionalProperties, "responderAccessCode")
		delete(additionalProperties, "respondentMetadata")
		delete(additionalProperties, "answers")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResponseSubmissionRequest struct {
	value *ResponseSubmissionRequest
	isSet bool
}

func (v NullableResponseSubmissionRequest) Get() *ResponseSubmissionRequest {
	return v.value
}

func (v *NullableResponseSubmissionRequest) Set(val *ResponseSubmissionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseSubmissionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseSubmissionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseSubmissionRequest(val *ResponseSubmissionRequest) *NullableResponseSubmissionRequest {
	return &NullableResponseSubmissionRequest{value: val, isSet: true}
}

func (v NullableResponseSubmissionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseSubmissionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


