/*
Survey Engine MVP API

Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the CampaignResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignResponse{}

// CampaignResponse struct for CampaignResponse
type CampaignResponse struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	SurveyId *string `json:"surveyId,omitempty"`
	SurveySnapshotId *string `json:"surveySnapshotId,omitempty"`
	DefaultWeightProfileId *string `json:"defaultWeightProfileId,omitempty"`
	AuthMode *string `json:"authMode,omitempty"`
	Status *string `json:"status,omitempty"`
	Active *bool `json:"active,omitempty"`
	CreatedBy *string `json:"createdBy,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedBy *string `json:"updatedBy,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CampaignResponse CampaignResponse

// NewCampaignResponse instantiates a new CampaignResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignResponse() *CampaignResponse {
	this := CampaignResponse{}
	return &this
}

// NewCampaignResponseWithDefaults instantiates a new CampaignResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignResponseWithDefaults() *CampaignResponse {
	this := CampaignResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CampaignResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CampaignResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CampaignResponse) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CampaignResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CampaignResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CampaignResponse) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CampaignResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CampaignResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CampaignResponse) SetDescription(v string) {
	o.Description = &v
}

// GetSurveyId returns the SurveyId field value if set, zero value otherwise.
func (o *CampaignResponse) GetSurveyId() string {
	if o == nil || IsNil(o.SurveyId) {
		var ret string
		return ret
	}
	return *o.SurveyId
}

// GetSurveyIdOk returns a tuple with the SurveyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignResponse) GetSurveyIdOk() (*string, bool) {
	if o == nil || IsNil(o.SurveyId) {
		return nil, false
	}
	return o.SurveyId, true
}

// HasSurveyId returns a boolean if a field has been set.
func (o *CampaignResponse) HasSurveyId() bool {
	if o != nil && !IsNil(o.SurveyId) {
		return true
	}

	return false
}

// SetSurveyId gets a reference to the given string and assigns it to the SurveyId field.
func (o *CampaignResponse) SetSurveyId(v string) {
	o.SurveyId = &v
}

// GetSurveySnapshotId returns the SurveySnapshotId field value if set, zero value otherwise.
func (o *CampaignResponse) GetSurveySnapshotId() string {
	if o == nil || IsNil(o.SurveySnapshotId) {
		var ret string
		return ret
	}
	return *o.SurveySnapshotId
}

// GetSurveySnapshotIdOk returns a tuple with the SurveySnapshotId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignResponse) GetSurveySnapshotIdOk() (*string, bool) {
	if o == nil || IsNil(o.SurveySnapshotId) {
		return nil, false
	}
	return o.SurveySnapshotId, true
}

// HasSurveySnapshotId returns a boolean if a field has been set.
func (o *CampaignResponse) HasSurveySnapshotId() bool {
	if o != nil && !IsNil(o.SurveySnapshotId) {
		return true
	}

	return false
}

// SetSurveySnapshotId gets a reference to the given string and assigns it to the SurveySnapshotId field.
func (o *CampaignResponse) SetSurveySnapshotId(v string) {
	o.SurveySnapshotId = &v
}

// GetDefaultWeightProfileId returns the DefaultWeightProfileId field value if set, zero value otherwise.
func (o *CampaignResponse) GetDefaultWeightProfileId() string {
	if o == nil || IsNil(o.DefaultWeightProfileId) {
		var ret string
		return ret
	}
	return *o.DefaultWeightProfileId
}

// GetDefaultWeightProfileIdOk returns a tuple with the DefaultWeightProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignResponse) GetDefaultWeightProfileIdOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultWeightProfileId) {
		return nil, false
	}
	return o.DefaultWeightProfileId, true
}

// HasDefaultWeightProfileId returns a boolean if a field has been set.
func (o *CampaignResponse) HasDefaultWeightProfileId() bool {
	if o != nil && !IsNil(o.DefaultWeightProfileId) {
		return true
	}

	return false
}

// SetDefaultWeightProfileId gets a reference to the given string and assigns it to the DefaultWeightProfileId field.
func (o *CampaignResponse) SetDefaultWeightProfileId(v string) {
	o.DefaultWeightProfileId = &v
}

// GetAuthMode returns the AuthMode field value if set, zero value otherwise.
func (o *CampaignResponse) GetAuthMode() string {
	if o == nil || IsNil(o.AuthMode) {
		var ret string
		return ret
	}
	return *o.AuthMode
}

// GetAuthModeOk returns a tuple with the AuthMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignResponse) GetAuthModeOk() (*string, bool) {
	if o == nil || IsNil(o.AuthMode) {
		return nil, false
	}
	return o.AuthMode, true
}

// HasAuthMode returns a boolean if a field has been set.
func (o *CampaignResponse) HasAuthMode() bool {
	if o != nil && !IsNil(o.AuthMode) {
		return true
	}

	return false
}

// SetAuthMode gets a reference to the given string and assigns it to the AuthMode field.
func (o *CampaignResponse) SetAuthMode(v string) {
	o.AuthMode = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CampaignResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CampaignResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CampaignResponse) SetStatus(v string) {
	o.Status = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *CampaignResponse) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignResponse) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *CampaignResponse) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *CampaignResponse) SetActive(v bool) {
	o.Active = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *CampaignResponse) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignResponse) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *CampaignResponse) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *CampaignResponse) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CampaignResponse) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CampaignResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *CampaignResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedBy returns the UpdatedBy field value if set, zero value otherwise.
func (o *CampaignResponse) GetUpdatedBy() string {
	if o == nil || IsNil(o.UpdatedBy) {
		var ret string
		return ret
	}
	return *o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignResponse) GetUpdatedByOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedBy) {
		return nil, false
	}
	return o.UpdatedBy, true
}

// HasUpdatedBy returns a boolean if a field has been set.
func (o *CampaignResponse) HasUpdatedBy() bool {
	if o != nil && !IsNil(o.UpdatedBy) {
		return true
	}

	return false
}

// SetUpdatedBy gets a reference to the given string and assigns it to the UpdatedBy field.
func (o *CampaignResponse) SetUpdatedBy(v string) {
	o.UpdatedBy = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *CampaignResponse) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *CampaignResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *CampaignResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o CampaignResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.SurveyId) {
		toSerialize["surveyId"] = o.SurveyId
	}
	if !IsNil(o.SurveySnapshotId) {
		toSerialize["surveySnapshotId"] = o.SurveySnapshotId
	}
	if !IsNil(o.DefaultWeightProfileId) {
		toSerialize["defaultWeightProfileId"] = o.DefaultWeightProfileId
	}
	if !IsNil(o.AuthMode) {
		toSerialize["authMode"] = o.AuthMode
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["createdBy"] = o.CreatedBy
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedBy) {
		toSerialize["updatedBy"] = o.UpdatedBy
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CampaignResponse) UnmarshalJSON(data []byte) (err error) {
	varCampaignResponse := _CampaignResponse{}

	err = json.Unmarshal(data, &varCampaignResponse)

	if err != nil {
		return err
	}

	*o = CampaignResponse(varCampaignResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "surveyId")
		delete(additionalProperties, "surveySnapshotId")
		delete(additionalProperties, "defaultWeightProfileId")
		delete(additionalProperties, "authMode")
		delete(additionalProperties, "status")
		delete(additionalProperties, "active")
		delete(additionalProperties, "createdBy")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedBy")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCampaignResponse struct {
	value *CampaignResponse
	isSet bool
}

func (v NullableCampaignResponse) Get() *CampaignResponse {
	return v.value
}

func (v *NullableCampaignResponse) Set(val *CampaignResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignResponse(val *CampaignResponse) *NullableCampaignResponse {
	return &NullableCampaignResponse{value: val, isSet: true}
}

func (v NullableCampaignResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


