/*
Survey Engine MVP API

Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CampaignPreviewResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignPreviewResponse{}

// CampaignPreviewResponse struct for CampaignPreviewResponse
type CampaignPreviewResponse struct {
	CampaignId *string `json:"campaignId,omitempty"`
	TenantId *string `json:"tenantId,omitempty"`
	CampaignName *string `json:"campaignName,omitempty"`
	CampaignStatus *string `json:"campaignStatus,omitempty"`
	AuthMode *string `json:"authMode,omitempty"`
	SurveyId *string `json:"surveyId,omitempty"`
	SurveyTitle *string `json:"surveyTitle,omitempty"`
	SurveyDescription *string `json:"surveyDescription,omitempty"`
	ShowQuestionNumbers *bool `json:"showQuestionNumbers,omitempty"`
	ShowProgressIndicator *bool `json:"showProgressIndicator,omitempty"`
	AllowBackButton *bool `json:"allowBackButton,omitempty"`
	StartMessage *string `json:"startMessage,omitempty"`
	FinishMessage *string `json:"finishMessage,omitempty"`
	HeaderHtml *string `json:"headerHtml,omitempty"`
	FooterHtml *string `json:"footerHtml,omitempty"`
	CollectName *bool `json:"collectName,omitempty"`
	CollectEmail *bool `json:"collectEmail,omitempty"`
	CollectPhone *bool `json:"collectPhone,omitempty"`
	CollectAddress *bool `json:"collectAddress,omitempty"`
	Pages []CampaignPreviewResponsePagesInner `json:"pages,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CampaignPreviewResponse CampaignPreviewResponse

// NewCampaignPreviewResponse instantiates a new CampaignPreviewResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignPreviewResponse() *CampaignPreviewResponse {
	this := CampaignPreviewResponse{}
	return &this
}

// NewCampaignPreviewResponseWithDefaults instantiates a new CampaignPreviewResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignPreviewResponseWithDefaults() *CampaignPreviewResponse {
	this := CampaignPreviewResponse{}
	return &this
}

// GetCampaignId returns the CampaignId field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetCampaignId() string {
	if o == nil || IsNil(o.CampaignId) {
		var ret string
		return ret
	}
	return *o.CampaignId
}

// GetCampaignIdOk returns a tuple with the CampaignId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetCampaignIdOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignId) {
		return nil, false
	}
	return o.CampaignId, true
}

// HasCampaignId returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasCampaignId() bool {
	if o != nil && !IsNil(o.CampaignId) {
		return true
	}

	return false
}

// SetCampaignId gets a reference to the given string and assigns it to the CampaignId field.
func (o *CampaignPreviewResponse) SetCampaignId(v string) {
	o.CampaignId = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CampaignPreviewResponse) SetTenantId(v string) {
	o.TenantId = &v
}

// GetCampaignName returns the CampaignName field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetCampaignName() string {
	if o == nil || IsNil(o.CampaignName) {
		var ret string
		return ret
	}
	return *o.CampaignName
}

// GetCampaignNameOk returns a tuple with the CampaignName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetCampaignNameOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignName) {
		return nil, false
	}
	return o.CampaignName, true
}

// HasCampaignName returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasCampaignName() bool {
	if o != nil && !IsNil(o.CampaignName) {
		return true
	}

	return false
}

// SetCampaignName gets a reference to the given string and assigns it to the CampaignName field.
func (o *CampaignPreviewResponse) SetCampaignName(v string) {
	o.CampaignName = &v
}

// GetCampaignStatus returns the CampaignStatus field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetCampaignStatus() string {
	if o == nil || IsNil(o.CampaignStatus) {
		var ret string
		return ret
	}
	return *o.CampaignStatus
}

// GetCampaignStatusOk returns a tuple with the CampaignStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetCampaignStatusOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignStatus) {
		return nil, false
	}
	return o.CampaignStatus, true
}

// HasCampaignStatus returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasCampaignStatus() bool {
	if o != nil && !IsNil(o.CampaignStatus) {
		return true
	}

	return false
}

// SetCampaignStatus gets a reference to the given string and assigns it to the CampaignStatus field.
func (o *CampaignPreviewResponse) SetCampaignStatus(v string) {
	o.CampaignStatus = &v
}

// GetAuthMode returns the AuthMode field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetAuthMode() string {
	if o == nil || IsNil(o.AuthMode) {
		var ret string
		return ret
	}
	return *o.AuthMode
}

// GetAuthModeOk returns a tuple with the AuthMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetAuthModeOk() (*string, bool) {
	if o == nil || IsNil(o.AuthMode) {
		return nil, false
	}
	return o.AuthMode, true
}

// HasAuthMode returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasAuthMode() bool {
	if o != nil && !IsNil(o.AuthMode) {
		return true
	}

	return false
}

// SetAuthMode gets a reference to the given string and assigns it to the AuthMode field.
func (o *CampaignPreviewResponse) SetAuthMode(v string) {
	o.AuthMode = &v
}

// GetSurveyId returns the SurveyId field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetSurveyId() string {
	if o == nil || IsNil(o.SurveyId) {
		var ret string
		return ret
	}
	return *o.SurveyId
}

// GetSurveyIdOk returns a tuple with the SurveyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetSurveyIdOk() (*string, bool) {
	if o == nil || IsNil(o.SurveyId) {
		return nil, false
	}
	return o.SurveyId, true
}

// HasSurveyId returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasSurveyId() bool {
	if o != nil && !IsNil(o.SurveyId) {
		return true
	}

	return false
}

// SetSurveyId gets a reference to the given string and assigns it to the SurveyId field.
func (o *CampaignPreviewResponse) SetSurveyId(v string) {
	o.SurveyId = &v
}

// GetSurveyTitle returns the SurveyTitle field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetSurveyTitle() string {
	if o == nil || IsNil(o.SurveyTitle) {
		var ret string
		return ret
	}
	return *o.SurveyTitle
}

// GetSurveyTitleOk returns a tuple with the SurveyTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetSurveyTitleOk() (*string, bool) {
	if o == nil || IsNil(o.SurveyTitle) {
		return nil, false
	}
	return o.SurveyTitle, true
}

// HasSurveyTitle returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasSurveyTitle() bool {
	if o != nil && !IsNil(o.SurveyTitle) {
		return true
	}

	return false
}

// SetSurveyTitle gets a reference to the given string and assigns it to the SurveyTitle field.
func (o *CampaignPreviewResponse) SetSurveyTitle(v string) {
	o.SurveyTitle = &v
}

// GetSurveyDescription returns the SurveyDescription field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetSurveyDescription() string {
	if o == nil || IsNil(o.SurveyDescription) {
		var ret string
		return ret
	}
	return *o.SurveyDescription
}

// GetSurveyDescriptionOk returns a tuple with the SurveyDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetSurveyDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.SurveyDescription) {
		return nil, false
	}
	return o.SurveyDescription, true
}

// HasSurveyDescription returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasSurveyDescription() bool {
	if o != nil && !IsNil(o.SurveyDescription) {
		return true
	}

	return false
}

// SetSurveyDescription gets a reference to the given string and assigns it to the SurveyDescription field.
func (o *CampaignPreviewResponse) SetSurveyDescription(v string) {
	o.SurveyDescription = &v
}

// GetShowQuestionNumbers returns the ShowQuestionNumbers field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetShowQuestionNumbers() bool {
	if o == nil || IsNil(o.ShowQuestionNumbers) {
		var ret bool
		return ret
	}
	return *o.ShowQuestionNumbers
}

// GetShowQuestionNumbersOk returns a tuple with the ShowQuestionNumbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetShowQuestionNumbersOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowQuestionNumbers) {
		return nil, false
	}
	return o.ShowQuestionNumbers, true
}

// HasShowQuestionNumbers returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasShowQuestionNumbers() bool {
	if o != nil && !IsNil(o.ShowQuestionNumbers) {
		return true
	}

	return false
}

// SetShowQuestionNumbers gets a reference to the given bool and assigns it to the ShowQuestionNumbers field.
func (o *CampaignPreviewResponse) SetShowQuestionNumbers(v bool) {
	o.ShowQuestionNumbers = &v
}

// GetShowProgressIndicator returns the ShowProgressIndicator field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetShowProgressIndicator() bool {
	if o == nil || IsNil(o.ShowProgressIndicator) {
		var ret bool
		return ret
	}
	return *o.ShowProgressIndicator
}

// GetShowProgressIndicatorOk returns a tuple with the ShowProgressIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetShowProgressIndicatorOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowProgressIndicator) {
		return nil, false
	}
	return o.ShowProgressIndicator, true
}

// HasShowProgressIndicator returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasShowProgressIndicator() bool {
	if o != nil && !IsNil(o.ShowProgressIndicator) {
		return true
	}

	return false
}

// SetShowProgressIndicator gets a reference to the given bool and assigns it to the ShowProgressIndicator field.
func (o *CampaignPreviewResponse) SetShowProgressIndicator(v bool) {
	o.ShowProgressIndicator = &v
}

// GetAllowBackButton returns the AllowBackButton field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetAllowBackButton() bool {
	if o == nil || IsNil(o.AllowBackButton) {
		var ret bool
		return ret
	}
	return *o.AllowBackButton
}

// GetAllowBackButtonOk returns a tuple with the AllowBackButton field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetAllowBackButtonOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowBackButton) {
		return nil, false
	}
	return o.AllowBackButton, true
}

// HasAllowBackButton returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasAllowBackButton() bool {
	if o != nil && !IsNil(o.AllowBackButton) {
		return true
	}

	return false
}

// SetAllowBackButton gets a reference to the given bool and assigns it to the AllowBackButton field.
func (o *CampaignPreviewResponse) SetAllowBackButton(v bool) {
	o.AllowBackButton = &v
}

// GetStartMessage returns the StartMessage field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetStartMessage() string {
	if o == nil || IsNil(o.StartMessage) {
		var ret string
		return ret
	}
	return *o.StartMessage
}

// GetStartMessageOk returns a tuple with the StartMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetStartMessageOk() (*string, bool) {
	if o == nil || IsNil(o.StartMessage) {
		return nil, false
	}
	return o.StartMessage, true
}

// HasStartMessage returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasStartMessage() bool {
	if o != nil && !IsNil(o.StartMessage) {
		return true
	}

	return false
}

// SetStartMessage gets a reference to the given string and assigns it to the StartMessage field.
func (o *CampaignPreviewResponse) SetStartMessage(v string) {
	o.StartMessage = &v
}

// GetFinishMessage returns the FinishMessage field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetFinishMessage() string {
	if o == nil || IsNil(o.FinishMessage) {
		var ret string
		return ret
	}
	return *o.FinishMessage
}

// GetFinishMessageOk returns a tuple with the FinishMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetFinishMessageOk() (*string, bool) {
	if o == nil || IsNil(o.FinishMessage) {
		return nil, false
	}
	return o.FinishMessage, true
}

// HasFinishMessage returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasFinishMessage() bool {
	if o != nil && !IsNil(o.FinishMessage) {
		return true
	}

	return false
}

// SetFinishMessage gets a reference to the given string and assigns it to the FinishMessage field.
func (o *CampaignPreviewResponse) SetFinishMessage(v string) {
	o.FinishMessage = &v
}

// GetHeaderHtml returns the HeaderHtml field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetHeaderHtml() string {
	if o == nil || IsNil(o.HeaderHtml) {
		var ret string
		return ret
	}
	return *o.HeaderHtml
}

// GetHeaderHtmlOk returns a tuple with the HeaderHtml field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetHeaderHtmlOk() (*string, bool) {
	if o == nil || IsNil(o.HeaderHtml) {
		return nil, false
	}
	return o.HeaderHtml, true
}

// HasHeaderHtml returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasHeaderHtml() bool {
	if o != nil && !IsNil(o.HeaderHtml) {
		return true
	}

	return false
}

// SetHeaderHtml gets a reference to the given string and assigns it to the HeaderHtml field.
func (o *CampaignPreviewResponse) SetHeaderHtml(v string) {
	o.HeaderHtml = &v
}

// GetFooterHtml returns the FooterHtml field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetFooterHtml() string {
	if o == nil || IsNil(o.FooterHtml) {
		var ret string
		return ret
	}
	return *o.FooterHtml
}

// GetFooterHtmlOk returns a tuple with the FooterHtml field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetFooterHtmlOk() (*string, bool) {
	if o == nil || IsNil(o.FooterHtml) {
		return nil, false
	}
	return o.FooterHtml, true
}

// HasFooterHtml returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasFooterHtml() bool {
	if o != nil && !IsNil(o.FooterHtml) {
		return true
	}

	return false
}

// SetFooterHtml gets a reference to the given string and assigns it to the FooterHtml field.
func (o *CampaignPreviewResponse) SetFooterHtml(v string) {
	o.FooterHtml = &v
}

// GetCollectName returns the CollectName field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetCollectName() bool {
	if o == nil || IsNil(o.CollectName) {
		var ret bool
		return ret
	}
	return *o.CollectName
}

// GetCollectNameOk returns a tuple with the CollectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetCollectNameOk() (*bool, bool) {
	if o == nil || IsNil(o.CollectName) {
		return nil, false
	}
	return o.CollectName, true
}

// HasCollectName returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasCollectName() bool {
	if o != nil && !IsNil(o.CollectName) {
		return true
	}

	return false
}

// SetCollectName gets a reference to the given bool and assigns it to the CollectName field.
func (o *CampaignPreviewResponse) SetCollectName(v bool) {
	o.CollectName = &v
}

// GetCollectEmail returns the CollectEmail field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetCollectEmail() bool {
	if o == nil || IsNil(o.CollectEmail) {
		var ret bool
		return ret
	}
	return *o.CollectEmail
}

// GetCollectEmailOk returns a tuple with the CollectEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetCollectEmailOk() (*bool, bool) {
	if o == nil || IsNil(o.CollectEmail) {
		return nil, false
	}
	return o.CollectEmail, true
}

// HasCollectEmail returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasCollectEmail() bool {
	if o != nil && !IsNil(o.CollectEmail) {
		return true
	}

	return false
}

// SetCollectEmail gets a reference to the given bool and assigns it to the CollectEmail field.
func (o *CampaignPreviewResponse) SetCollectEmail(v bool) {
	o.CollectEmail = &v
}

// GetCollectPhone returns the CollectPhone field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetCollectPhone() bool {
	if o == nil || IsNil(o.CollectPhone) {
		var ret bool
		return ret
	}
	return *o.CollectPhone
}

// GetCollectPhoneOk returns a tuple with the CollectPhone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetCollectPhoneOk() (*bool, bool) {
	if o == nil || IsNil(o.CollectPhone) {
		return nil, false
	}
	return o.CollectPhone, true
}

// HasCollectPhone returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasCollectPhone() bool {
	if o != nil && !IsNil(o.CollectPhone) {
		return true
	}

	return false
}

// SetCollectPhone gets a reference to the given bool and assigns it to the CollectPhone field.
func (o *CampaignPreviewResponse) SetCollectPhone(v bool) {
	o.CollectPhone = &v
}

// GetCollectAddress returns the CollectAddress field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetCollectAddress() bool {
	if o == nil || IsNil(o.CollectAddress) {
		var ret bool
		return ret
	}
	return *o.CollectAddress
}

// GetCollectAddressOk returns a tuple with the CollectAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetCollectAddressOk() (*bool, bool) {
	if o == nil || IsNil(o.CollectAddress) {
		return nil, false
	}
	return o.CollectAddress, true
}

// HasCollectAddress returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasCollectAddress() bool {
	if o != nil && !IsNil(o.CollectAddress) {
		return true
	}

	return false
}

// SetCollectAddress gets a reference to the given bool and assigns it to the CollectAddress field.
func (o *CampaignPreviewResponse) SetCollectAddress(v bool) {
	o.CollectAddress = &v
}

// GetPages returns the Pages field value if set, zero value otherwise.
func (o *CampaignPreviewResponse) GetPages() []CampaignPreviewResponsePagesInner {
	if o == nil || IsNil(o.Pages) {
		var ret []CampaignPreviewResponsePagesInner
		return ret
	}
	return o.Pages
}

// GetPagesOk returns a tuple with the Pages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignPreviewResponse) GetPagesOk() ([]CampaignPreviewResponsePagesInner, bool) {
	if o == nil || IsNil(o.Pages) {
		return nil, false
	}
	return o.Pages, true
}

// HasPages returns a boolean if a field has been set.
func (o *CampaignPreviewResponse) HasPages() bool {
	if o != nil && !IsNil(o.Pages) {
		return true
	}

	return false
}

// SetPages gets a reference to the given []CampaignPreviewResponsePagesInner and assigns it to the Pages field.
func (o *CampaignPreviewResponse) SetPages(v []CampaignPreviewResponsePagesInner) {
	o.Pages = v
}

func (o CampaignPreviewResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignPreviewResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CampaignId) {
		toSerialize["campaignId"] = o.CampaignId
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.CampaignName) {
		toSerialize["campaignName"] = o.CampaignName
	}
	if !IsNil(o.CampaignStatus) {
		toSerialize["campaignStatus"] = o.CampaignStatus
	}
	if !IsNil(o.AuthMode) {
		toSerialize["authMode"] = o.AuthMode
	}
	if !IsNil(o.SurveyId) {
		toSerialize["surveyId"] = o.SurveyId
	}
	if !IsNil(o.SurveyTitle) {
		toSerialize["surveyTitle"] = o.SurveyTitle
	}
	if !IsNil(o.SurveyDescription) {
		toSerialize["surveyDescription"] = o.SurveyDescription
	}
	if !IsNil(o.ShowQuestionNumbers) {
		toSerialize["showQuestionNumbers"] = o.ShowQuestionNumbers
	}
	if !IsNil(o.ShowProgressIndicator) {
		toSerialize["showProgressIndicator"] = o.ShowProgressIndicator
	}
	if !IsNil(o.AllowBackButton) {
		toSerialize["allowBackButton"] = o.AllowBackButton
	}
	if !IsNil(o.StartMessage) {
		toSerialize["startMessage"] = o.StartMessage
	}
	if !IsNil(o.FinishMessage) {
		toSerialize["finishMessage"] = o.FinishMessage
	}
	if !IsNil(o.HeaderHtml) {
		toSerialize["headerHtml"] = o.HeaderHtml
	}
	if !IsNil(o.FooterHtml) {
		toSerialize["footerHtml"] = o.FooterHtml
	}
	if !IsNil(o.CollectName) {
		toSerialize["collectName"] = o.CollectName
	}
	if !IsNil(o.CollectEmail) {
		toSerialize["collectEmail"] = o.CollectEmail
	}
	if !IsNil(o.CollectPhone) {
		toSerialize["collectPhone"] = o.CollectPhone
	}
	if !IsNil(o.CollectAddress) {
		toSerialize["collectAddress"] = o.CollectAddress
	}
	if !IsNil(o.Pages) {
		toSerialize["pages"] = o.Pages
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CampaignPreviewResponse) UnmarshalJSON(data []byte) (err error) {
	varCampaignPreviewResponse := _CampaignPreviewResponse{}

	err = json.Unmarshal(data, &varCampaignPreviewResponse)

	if err != nil {
		return err
	}

	*o = CampaignPreviewResponse(varCampaignPreviewResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "campaignId")
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "campaignName")
		delete(additionalProperties, "campaignStatus")
		delete(additionalProperties, "authMode")
		delete(additionalProperties, "surveyId")
		delete(additionalProperties, "surveyTitle")
		delete(additionalProperties, "surveyDescription")
		delete(additionalProperties, "showQuestionNumbers")
		delete(additionalProperties, "showProgressIndicator")
		delete(additionalProperties, "allowBackButton")
		delete(additionalProperties, "startMessage")
		delete(additionalProperties, "finishMessage")
		delete(additionalProperties, "headerHtml")
		delete(additionalProperties, "footerHtml")
		delete(additionalProperties, "collectName")
		delete(additionalProperties, "collectEmail")
		delete(additionalProperties, "collectPhone")
		delete(additionalProperties, "collectAddress")
		delete(additionalProperties, "pages")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCampaignPreviewResponse struct {
	value *CampaignPreviewResponse
	isSet bool
}

func (v NullableCampaignPreviewResponse) Get() *CampaignPreviewResponse {
	return v.value
}

func (v *NullableCampaignPreviewResponse) Set(val *CampaignPreviewResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignPreviewResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignPreviewResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignPreviewResponse(val *CampaignPreviewResponse) *NullableCampaignPreviewResponse {
	return &NullableCampaignPreviewResponse{value: val, isSet: true}
}

func (v NullableCampaignPreviewResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignPreviewResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


