/*
 * Survey Engine MVP API
 * Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.AuthResponse;
import org.openapitools.client.model.AuthUserResponse;
import org.openapitools.client.model.CsrfTokenResponse;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.LoginRequest;
import org.openapitools.client.model.RefreshTokenRequest;
import org.openapitools.client.model.RegisterRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AdminAuthenticationApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AdminAuthenticationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AdminAuthenticationApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getCsrfToken
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> CSRF token returned </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCsrfTokenCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/admin/auth/csrf";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getCsrfTokenValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getCsrfTokenCall(_callback);

    }

    /**
     * Get CSRF token for browser cookie session mode
     * Why this endpoint is needed: Browser-based admin sessions use HttpOnly auth cookies and require CSRF token submission for state-changing requests.  What this endpoint does: It returns the current CSRF token value and ensures CSRF cookie state is initialized for the caller.  How this endpoint does it: Spring Security creates/loads token via cookie token repository, controller returns it as a simple JSON payload. 
     * @return CsrfTokenResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> CSRF token returned </td><td>  -  </td></tr>
     </table>
     */
    public CsrfTokenResponse getCsrfToken() throws ApiException {
        ApiResponse<CsrfTokenResponse> localVarResp = getCsrfTokenWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Get CSRF token for browser cookie session mode
     * Why this endpoint is needed: Browser-based admin sessions use HttpOnly auth cookies and require CSRF token submission for state-changing requests.  What this endpoint does: It returns the current CSRF token value and ensures CSRF cookie state is initialized for the caller.  How this endpoint does it: Spring Security creates/loads token via cookie token repository, controller returns it as a simple JSON payload. 
     * @return ApiResponse&lt;CsrfTokenResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> CSRF token returned </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CsrfTokenResponse> getCsrfTokenWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getCsrfTokenValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<CsrfTokenResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get CSRF token for browser cookie session mode (asynchronously)
     * Why this endpoint is needed: Browser-based admin sessions use HttpOnly auth cookies and require CSRF token submission for state-changing requests.  What this endpoint does: It returns the current CSRF token value and ensures CSRF cookie state is initialized for the caller.  How this endpoint does it: Spring Security creates/loads token via cookie token repository, controller returns it as a simple JSON payload. 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> CSRF token returned </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCsrfTokenAsync(final ApiCallback<CsrfTokenResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getCsrfTokenValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<CsrfTokenResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getCurrentAdmin
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Current admin profile returned </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCurrentAdminCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/admin/auth/me";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getCurrentAdminValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getCurrentAdminCall(_callback);

    }

    /**
     * Retrieve current authenticated admin profile
     * Why this endpoint is needed: Frontend needs a lightweight session-hydration endpoint after reload to confirm authentication and tenant context.  What this endpoint does: It returns current authenticated user&#39;s profile details (no tokens).  How this endpoint does it: JWT filter populates security/tenant context from cookie or bearer token, and controller maps context to response DTO. 
     * @return AuthUserResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Current admin profile returned </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
     </table>
     */
    public AuthUserResponse getCurrentAdmin() throws ApiException {
        ApiResponse<AuthUserResponse> localVarResp = getCurrentAdminWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Retrieve current authenticated admin profile
     * Why this endpoint is needed: Frontend needs a lightweight session-hydration endpoint after reload to confirm authentication and tenant context.  What this endpoint does: It returns current authenticated user&#39;s profile details (no tokens).  How this endpoint does it: JWT filter populates security/tenant context from cookie or bearer token, and controller maps context to response DTO. 
     * @return ApiResponse&lt;AuthUserResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Current admin profile returned </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AuthUserResponse> getCurrentAdminWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getCurrentAdminValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<AuthUserResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve current authenticated admin profile (asynchronously)
     * Why this endpoint is needed: Frontend needs a lightweight session-hydration endpoint after reload to confirm authentication and tenant context.  What this endpoint does: It returns current authenticated user&#39;s profile details (no tokens).  How this endpoint does it: JWT filter populates security/tenant context from cookie or bearer token, and controller maps context to response DTO. 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Current admin profile returned </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCurrentAdminAsync(final ApiCallback<AuthUserResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getCurrentAdminValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<AuthUserResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for loginAdmin
     * @param loginRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Login successful and new auth cookies issued </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Referenced resource does not exist or is not visible in tenant scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call loginAdminCall(@javax.annotation.Nonnull LoginRequest loginRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = loginRequest;

        // create path and map variables
        String localVarPath = "/api/v1/admin/auth/login";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call loginAdminValidateBeforeCall(@javax.annotation.Nonnull LoginRequest loginRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'loginRequest' is set
        if (loginRequest == null) {
            throw new ApiException("Missing the required parameter 'loginRequest' when calling loginAdmin(Async)");
        }

        return loginAdminCall(loginRequest, _callback);

    }

    /**
     * Log in an existing admin and issue fresh auth cookies
     * Why this endpoint is needed: Admin operators need a secure login path to start authenticated management sessions for tenant resources.  What this endpoint does: It authenticates the admin using email/password, revokes prior refresh tokens for session hygiene, and issues a fresh access token plus a new refresh token as HttpOnly cookies.  How this endpoint does it: The service verifies account status and password hash, rotates refresh-token state to avoid stale session reuse, and controller writes cookies while returning safe user context payload. 
     * @param loginRequest  (required)
     * @return AuthUserResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Login successful and new auth cookies issued </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Referenced resource does not exist or is not visible in tenant scope </td><td>  -  </td></tr>
     </table>
     */
    public AuthUserResponse loginAdmin(@javax.annotation.Nonnull LoginRequest loginRequest) throws ApiException {
        ApiResponse<AuthUserResponse> localVarResp = loginAdminWithHttpInfo(loginRequest);
        return localVarResp.getData();
    }

    /**
     * Log in an existing admin and issue fresh auth cookies
     * Why this endpoint is needed: Admin operators need a secure login path to start authenticated management sessions for tenant resources.  What this endpoint does: It authenticates the admin using email/password, revokes prior refresh tokens for session hygiene, and issues a fresh access token plus a new refresh token as HttpOnly cookies.  How this endpoint does it: The service verifies account status and password hash, rotates refresh-token state to avoid stale session reuse, and controller writes cookies while returning safe user context payload. 
     * @param loginRequest  (required)
     * @return ApiResponse&lt;AuthUserResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Login successful and new auth cookies issued </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Referenced resource does not exist or is not visible in tenant scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AuthUserResponse> loginAdminWithHttpInfo(@javax.annotation.Nonnull LoginRequest loginRequest) throws ApiException {
        okhttp3.Call localVarCall = loginAdminValidateBeforeCall(loginRequest, null);
        Type localVarReturnType = new TypeToken<AuthUserResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Log in an existing admin and issue fresh auth cookies (asynchronously)
     * Why this endpoint is needed: Admin operators need a secure login path to start authenticated management sessions for tenant resources.  What this endpoint does: It authenticates the admin using email/password, revokes prior refresh tokens for session hygiene, and issues a fresh access token plus a new refresh token as HttpOnly cookies.  How this endpoint does it: The service verifies account status and password hash, rotates refresh-token state to avoid stale session reuse, and controller writes cookies while returning safe user context payload. 
     * @param loginRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Login successful and new auth cookies issued </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Referenced resource does not exist or is not visible in tenant scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call loginAdminAsync(@javax.annotation.Nonnull LoginRequest loginRequest, final ApiCallback<AuthUserResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = loginAdminValidateBeforeCall(loginRequest, _callback);
        Type localVarReturnType = new TypeToken<AuthUserResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for loginAdminTokenMode
     * @param loginRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Login successful and token payload returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Referenced resource does not exist or is not visible in tenant scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call loginAdminTokenModeCall(@javax.annotation.Nonnull LoginRequest loginRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = loginRequest;

        // create path and map variables
        String localVarPath = "/api/v1/admin/auth/token/login";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call loginAdminTokenModeValidateBeforeCall(@javax.annotation.Nonnull LoginRequest loginRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'loginRequest' is set
        if (loginRequest == null) {
            throw new ApiException("Missing the required parameter 'loginRequest' when calling loginAdminTokenMode(Async)");
        }

        return loginAdminTokenModeCall(loginRequest, _callback);

    }

    /**
     * Log in admin in headless token mode
     * Why this endpoint is needed: API clients and external automation flows need explicit JWT credentials in response body.  What this endpoint does: It authenticates admin credentials and returns fresh access/refresh tokens directly in payload.  How this endpoint does it: Service validates credentials, rotates refresh-token state, and controller returns AuthResponse DTO. 
     * @param loginRequest  (required)
     * @return AuthResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Login successful and token payload returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Referenced resource does not exist or is not visible in tenant scope </td><td>  -  </td></tr>
     </table>
     */
    public AuthResponse loginAdminTokenMode(@javax.annotation.Nonnull LoginRequest loginRequest) throws ApiException {
        ApiResponse<AuthResponse> localVarResp = loginAdminTokenModeWithHttpInfo(loginRequest);
        return localVarResp.getData();
    }

    /**
     * Log in admin in headless token mode
     * Why this endpoint is needed: API clients and external automation flows need explicit JWT credentials in response body.  What this endpoint does: It authenticates admin credentials and returns fresh access/refresh tokens directly in payload.  How this endpoint does it: Service validates credentials, rotates refresh-token state, and controller returns AuthResponse DTO. 
     * @param loginRequest  (required)
     * @return ApiResponse&lt;AuthResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Login successful and token payload returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Referenced resource does not exist or is not visible in tenant scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AuthResponse> loginAdminTokenModeWithHttpInfo(@javax.annotation.Nonnull LoginRequest loginRequest) throws ApiException {
        okhttp3.Call localVarCall = loginAdminTokenModeValidateBeforeCall(loginRequest, null);
        Type localVarReturnType = new TypeToken<AuthResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Log in admin in headless token mode (asynchronously)
     * Why this endpoint is needed: API clients and external automation flows need explicit JWT credentials in response body.  What this endpoint does: It authenticates admin credentials and returns fresh access/refresh tokens directly in payload.  How this endpoint does it: Service validates credentials, rotates refresh-token state, and controller returns AuthResponse DTO. 
     * @param loginRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Login successful and token payload returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Referenced resource does not exist or is not visible in tenant scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call loginAdminTokenModeAsync(@javax.annotation.Nonnull LoginRequest loginRequest, final ApiCallback<AuthResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = loginAdminTokenModeValidateBeforeCall(loginRequest, _callback);
        Type localVarReturnType = new TypeToken<AuthResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for logoutAdmin
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Logout completed and cookies cleared </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call logoutAdminCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/admin/auth/logout";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call logoutAdminValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return logoutAdminCall(_callback);

    }

    /**
     * Clear admin auth cookies
     * Why this endpoint is needed: Sessions must support explicit and secure sign-out to prevent lingering browser-side authentication state.  What this endpoint does: It clears access_token and refresh_token cookies.  How this endpoint does it: Controller writes both token cookies with maxAge&#x3D;0, path&#x3D;/, HttpOnly/Secure attributes. 
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Logout completed and cookies cleared </td><td>  -  </td></tr>
     </table>
     */
    public void logoutAdmin() throws ApiException {
        logoutAdminWithHttpInfo();
    }

    /**
     * Clear admin auth cookies
     * Why this endpoint is needed: Sessions must support explicit and secure sign-out to prevent lingering browser-side authentication state.  What this endpoint does: It clears access_token and refresh_token cookies.  How this endpoint does it: Controller writes both token cookies with maxAge&#x3D;0, path&#x3D;/, HttpOnly/Secure attributes. 
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Logout completed and cookies cleared </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> logoutAdminWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = logoutAdminValidateBeforeCall(null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Clear admin auth cookies (asynchronously)
     * Why this endpoint is needed: Sessions must support explicit and secure sign-out to prevent lingering browser-side authentication state.  What this endpoint does: It clears access_token and refresh_token cookies.  How this endpoint does it: Controller writes both token cookies with maxAge&#x3D;0, path&#x3D;/, HttpOnly/Secure attributes. 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Logout completed and cookies cleared </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call logoutAdminAsync(final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = logoutAdminValidateBeforeCall(_callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for refreshAdminToken
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Cookie rotation successful </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Referenced resource does not exist or is not visible in tenant scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call refreshAdminTokenCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/admin/auth/refresh";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call refreshAdminTokenValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return refreshAdminTokenCall(_callback);

    }

    /**
     * Rotate refresh cookie and issue a new admin session
     * Why this endpoint is needed: Access tokens are intentionally short-lived. A secure refresh mechanism is required to keep admins signed in without repeatedly collecting credentials.  What this endpoint does: It reads refresh token from HttpOnly cookie, validates it, rotates token state, and sets fresh access/refresh cookies.  How this endpoint does it: Controller extracts refresh_token cookie, service validates persistence state (including expiry/revocation), applies one-time-use rotation semantics, and controller rewrites secure cookies. 
     * @return AuthUserResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Cookie rotation successful </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Referenced resource does not exist or is not visible in tenant scope </td><td>  -  </td></tr>
     </table>
     */
    public AuthUserResponse refreshAdminToken() throws ApiException {
        ApiResponse<AuthUserResponse> localVarResp = refreshAdminTokenWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Rotate refresh cookie and issue a new admin session
     * Why this endpoint is needed: Access tokens are intentionally short-lived. A secure refresh mechanism is required to keep admins signed in without repeatedly collecting credentials.  What this endpoint does: It reads refresh token from HttpOnly cookie, validates it, rotates token state, and sets fresh access/refresh cookies.  How this endpoint does it: Controller extracts refresh_token cookie, service validates persistence state (including expiry/revocation), applies one-time-use rotation semantics, and controller rewrites secure cookies. 
     * @return ApiResponse&lt;AuthUserResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Cookie rotation successful </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Referenced resource does not exist or is not visible in tenant scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AuthUserResponse> refreshAdminTokenWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = refreshAdminTokenValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<AuthUserResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Rotate refresh cookie and issue a new admin session (asynchronously)
     * Why this endpoint is needed: Access tokens are intentionally short-lived. A secure refresh mechanism is required to keep admins signed in without repeatedly collecting credentials.  What this endpoint does: It reads refresh token from HttpOnly cookie, validates it, rotates token state, and sets fresh access/refresh cookies.  How this endpoint does it: Controller extracts refresh_token cookie, service validates persistence state (including expiry/revocation), applies one-time-use rotation semantics, and controller rewrites secure cookies. 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Cookie rotation successful </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Referenced resource does not exist or is not visible in tenant scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call refreshAdminTokenAsync(final ApiCallback<AuthUserResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = refreshAdminTokenValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<AuthUserResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for refreshAdminTokenMode
     * @param refreshTokenRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Token rotation successful </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call refreshAdminTokenModeCall(@javax.annotation.Nonnull RefreshTokenRequest refreshTokenRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = refreshTokenRequest;

        // create path and map variables
        String localVarPath = "/api/v1/admin/auth/token/refresh";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call refreshAdminTokenModeValidateBeforeCall(@javax.annotation.Nonnull RefreshTokenRequest refreshTokenRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'refreshTokenRequest' is set
        if (refreshTokenRequest == null) {
            throw new ApiException("Missing the required parameter 'refreshTokenRequest' when calling refreshAdminTokenMode(Async)");
        }

        return refreshAdminTokenModeCall(refreshTokenRequest, _callback);

    }

    /**
     * Refresh session in headless token mode
     * Why this endpoint is needed: Headless integrations need refresh-token rotation without cookie transport.  What this endpoint does: It validates provided refresh token and returns a rotated access/refresh token pair.  How this endpoint does it: Controller accepts RefreshTokenRequest payload and delegates to refresh-token rotation service. 
     * @param refreshTokenRequest  (required)
     * @return AuthResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Token rotation successful </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
     </table>
     */
    public AuthResponse refreshAdminTokenMode(@javax.annotation.Nonnull RefreshTokenRequest refreshTokenRequest) throws ApiException {
        ApiResponse<AuthResponse> localVarResp = refreshAdminTokenModeWithHttpInfo(refreshTokenRequest);
        return localVarResp.getData();
    }

    /**
     * Refresh session in headless token mode
     * Why this endpoint is needed: Headless integrations need refresh-token rotation without cookie transport.  What this endpoint does: It validates provided refresh token and returns a rotated access/refresh token pair.  How this endpoint does it: Controller accepts RefreshTokenRequest payload and delegates to refresh-token rotation service. 
     * @param refreshTokenRequest  (required)
     * @return ApiResponse&lt;AuthResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Token rotation successful </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AuthResponse> refreshAdminTokenModeWithHttpInfo(@javax.annotation.Nonnull RefreshTokenRequest refreshTokenRequest) throws ApiException {
        okhttp3.Call localVarCall = refreshAdminTokenModeValidateBeforeCall(refreshTokenRequest, null);
        Type localVarReturnType = new TypeToken<AuthResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Refresh session in headless token mode (asynchronously)
     * Why this endpoint is needed: Headless integrations need refresh-token rotation without cookie transport.  What this endpoint does: It validates provided refresh token and returns a rotated access/refresh token pair.  How this endpoint does it: Controller accepts RefreshTokenRequest payload and delegates to refresh-token rotation service. 
     * @param refreshTokenRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Token rotation successful </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call refreshAdminTokenModeAsync(@javax.annotation.Nonnull RefreshTokenRequest refreshTokenRequest, final ApiCallback<AuthResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = refreshAdminTokenModeValidateBeforeCall(refreshTokenRequest, _callback);
        Type localVarReturnType = new TypeToken<AuthResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for registerAdmin
     * @param registerRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Admin account created and authenticated session returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Requested action conflicts with current resource state </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call registerAdminCall(@javax.annotation.Nonnull RegisterRequest registerRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = registerRequest;

        // create path and map variables
        String localVarPath = "/api/v1/admin/auth/register";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call registerAdminValidateBeforeCall(@javax.annotation.Nonnull RegisterRequest registerRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'registerRequest' is set
        if (registerRequest == null) {
            throw new ApiException("Missing the required parameter 'registerRequest' when calling registerAdmin(Async)");
        }

        return registerAdminCall(registerRequest, _callback);

    }

    /**
     * Register a tenant admin account and bootstrap tenant access
     * Why this endpoint is needed: A brand-new subscriber needs a secure, first-class admin identity to operate the platform. Without this endpoint, onboarding would require manual platform-team intervention and would break self-service SaaS adoption.  What this endpoint does: It creates the first admin user for a tenant, ensures tenant provisioning exists, ensures a trial subscription exists, sets access/refresh tokens as HttpOnly cookies, and returns safe user context in response body.  How this endpoint does it: The service validates uniqueness of email, provisions tenant records when necessary, enforces admin-user quota policy, stores password hash securely, issues an engine-signed JWT access token, creates a refresh token row, and controller writes both tokens into secure cookies before returning AuthUserResponse. 
     * @param registerRequest  (required)
     * @return AuthUserResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Admin account created and authenticated session returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Requested action conflicts with current resource state </td><td>  -  </td></tr>
     </table>
     */
    public AuthUserResponse registerAdmin(@javax.annotation.Nonnull RegisterRequest registerRequest) throws ApiException {
        ApiResponse<AuthUserResponse> localVarResp = registerAdminWithHttpInfo(registerRequest);
        return localVarResp.getData();
    }

    /**
     * Register a tenant admin account and bootstrap tenant access
     * Why this endpoint is needed: A brand-new subscriber needs a secure, first-class admin identity to operate the platform. Without this endpoint, onboarding would require manual platform-team intervention and would break self-service SaaS adoption.  What this endpoint does: It creates the first admin user for a tenant, ensures tenant provisioning exists, ensures a trial subscription exists, sets access/refresh tokens as HttpOnly cookies, and returns safe user context in response body.  How this endpoint does it: The service validates uniqueness of email, provisions tenant records when necessary, enforces admin-user quota policy, stores password hash securely, issues an engine-signed JWT access token, creates a refresh token row, and controller writes both tokens into secure cookies before returning AuthUserResponse. 
     * @param registerRequest  (required)
     * @return ApiResponse&lt;AuthUserResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Admin account created and authenticated session returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Requested action conflicts with current resource state </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AuthUserResponse> registerAdminWithHttpInfo(@javax.annotation.Nonnull RegisterRequest registerRequest) throws ApiException {
        okhttp3.Call localVarCall = registerAdminValidateBeforeCall(registerRequest, null);
        Type localVarReturnType = new TypeToken<AuthUserResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Register a tenant admin account and bootstrap tenant access (asynchronously)
     * Why this endpoint is needed: A brand-new subscriber needs a secure, first-class admin identity to operate the platform. Without this endpoint, onboarding would require manual platform-team intervention and would break self-service SaaS adoption.  What this endpoint does: It creates the first admin user for a tenant, ensures tenant provisioning exists, ensures a trial subscription exists, sets access/refresh tokens as HttpOnly cookies, and returns safe user context in response body.  How this endpoint does it: The service validates uniqueness of email, provisions tenant records when necessary, enforces admin-user quota policy, stores password hash securely, issues an engine-signed JWT access token, creates a refresh token row, and controller writes both tokens into secure cookies before returning AuthUserResponse. 
     * @param registerRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Admin account created and authenticated session returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Requested action conflicts with current resource state </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call registerAdminAsync(@javax.annotation.Nonnull RegisterRequest registerRequest, final ApiCallback<AuthUserResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = registerAdminValidateBeforeCall(registerRequest, _callback);
        Type localVarReturnType = new TypeToken<AuthUserResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for registerAdminTokenMode
     * @param registerRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Admin registered and token payload returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Requested action conflicts with current resource state </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call registerAdminTokenModeCall(@javax.annotation.Nonnull RegisterRequest registerRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = registerRequest;

        // create path and map variables
        String localVarPath = "/api/v1/admin/auth/token/register";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call registerAdminTokenModeValidateBeforeCall(@javax.annotation.Nonnull RegisterRequest registerRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'registerRequest' is set
        if (registerRequest == null) {
            throw new ApiException("Missing the required parameter 'registerRequest' when calling registerAdminTokenMode(Async)");
        }

        return registerAdminTokenModeCall(registerRequest, _callback);

    }

    /**
     * Register admin in headless token mode
     * Why this endpoint is needed: Headless/API clients cannot reliably consume browser cookie flows and need explicit token payloads.  What this endpoint does: It performs the same registration flow as cookie mode but returns access/refresh tokens directly in response body.  How this endpoint does it: Service runs standard tenant bootstrap/registration pipeline and controller returns AuthResponse without writing cookies. 
     * @param registerRequest  (required)
     * @return AuthResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Admin registered and token payload returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Requested action conflicts with current resource state </td><td>  -  </td></tr>
     </table>
     */
    public AuthResponse registerAdminTokenMode(@javax.annotation.Nonnull RegisterRequest registerRequest) throws ApiException {
        ApiResponse<AuthResponse> localVarResp = registerAdminTokenModeWithHttpInfo(registerRequest);
        return localVarResp.getData();
    }

    /**
     * Register admin in headless token mode
     * Why this endpoint is needed: Headless/API clients cannot reliably consume browser cookie flows and need explicit token payloads.  What this endpoint does: It performs the same registration flow as cookie mode but returns access/refresh tokens directly in response body.  How this endpoint does it: Service runs standard tenant bootstrap/registration pipeline and controller returns AuthResponse without writing cookies. 
     * @param registerRequest  (required)
     * @return ApiResponse&lt;AuthResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Admin registered and token payload returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Requested action conflicts with current resource state </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AuthResponse> registerAdminTokenModeWithHttpInfo(@javax.annotation.Nonnull RegisterRequest registerRequest) throws ApiException {
        okhttp3.Call localVarCall = registerAdminTokenModeValidateBeforeCall(registerRequest, null);
        Type localVarReturnType = new TypeToken<AuthResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Register admin in headless token mode (asynchronously)
     * Why this endpoint is needed: Headless/API clients cannot reliably consume browser cookie flows and need explicit token payloads.  What this endpoint does: It performs the same registration flow as cookie mode but returns access/refresh tokens directly in response body.  How this endpoint does it: Service runs standard tenant bootstrap/registration pipeline and controller returns AuthResponse without writing cookies. 
     * @param registerRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Admin registered and token payload returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Requested action conflicts with current resource state </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call registerAdminTokenModeAsync(@javax.annotation.Nonnull RegisterRequest registerRequest, final ApiCallback<AuthResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = registerAdminTokenModeValidateBeforeCall(registerRequest, _callback);
        Type localVarReturnType = new TypeToken<AuthResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for revertImpersonation
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Impersonation context reverted </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call revertImpersonationCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/admin/auth/revert-impersonation";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call revertImpersonationValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return revertImpersonationCall(_callback);

    }

    /**
     * Restore original super-admin cookies after impersonation
     * Why this endpoint is needed: Super-admin support sessions must safely return from tenant impersonation to original privileged context.  What this endpoint does: It restores stashed super-admin auth cookies and clears temporary impersonation cookies.  How this endpoint does it: Cookie utility reads stashed &#x60;sa_*&#x60; cookies, rewrites primary auth cookies, and clears impersonation artifacts. 
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Impersonation context reverted </td><td>  -  </td></tr>
     </table>
     */
    public void revertImpersonation() throws ApiException {
        revertImpersonationWithHttpInfo();
    }

    /**
     * Restore original super-admin cookies after impersonation
     * Why this endpoint is needed: Super-admin support sessions must safely return from tenant impersonation to original privileged context.  What this endpoint does: It restores stashed super-admin auth cookies and clears temporary impersonation cookies.  How this endpoint does it: Cookie utility reads stashed &#x60;sa_*&#x60; cookies, rewrites primary auth cookies, and clears impersonation artifacts. 
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Impersonation context reverted </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> revertImpersonationWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = revertImpersonationValidateBeforeCall(null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Restore original super-admin cookies after impersonation (asynchronously)
     * Why this endpoint is needed: Super-admin support sessions must safely return from tenant impersonation to original privileged context.  What this endpoint does: It restores stashed super-admin auth cookies and clears temporary impersonation cookies.  How this endpoint does it: Cookie utility reads stashed &#x60;sa_*&#x60; cookies, rewrites primary auth cookies, and clears impersonation artifacts. 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Impersonation context reverted </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call revertImpersonationAsync(final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = revertImpersonationValidateBeforeCall(_callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
