/*
 * Survey Engine MVP API
 * Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.ErrorResponse;
import java.time.OffsetDateTime;
import org.openapitools.client.model.PageAuditLogResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AuditLogsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AuditLogsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AuditLogsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getPlatformAuditLogs
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 20)
     * @param action  (optional)
     * @param entityType  (optional)
     * @param tenantId  (optional)
     * @param actor  (optional)
     * @param from  (optional)
     * @param to  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platform audit logs returned </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not allowed by tenant/role/security policy </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPlatformAuditLogsCall(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String action, @javax.annotation.Nullable String entityType, @javax.annotation.Nullable String tenantId, @javax.annotation.Nullable String actor, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/admin/superadmin/audit-logs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (size != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("size", size));
        }

        if (action != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("action", action));
        }

        if (entityType != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("entityType", entityType));
        }

        if (tenantId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("tenantId", tenantId));
        }

        if (actor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("actor", actor));
        }

        if (from != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("from", from));
        }

        if (to != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("to", to));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPlatformAuditLogsValidateBeforeCall(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String action, @javax.annotation.Nullable String entityType, @javax.annotation.Nullable String tenantId, @javax.annotation.Nullable String actor, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, final ApiCallback _callback) throws ApiException {
        return getPlatformAuditLogsCall(page, size, action, entityType, tenantId, actor, from, to, _callback);

    }

    /**
     * Query platform-wide audit logs (SUPER_ADMIN)
     * Why this endpoint is needed: Super-admin operations require cross-tenant traceability for investigations and compliance.  What this endpoint does: It returns paged audit logs across all tenants with optional filters for actor/action/entity/tenant.  How this endpoint does it: Controller applies optional filter predicates and queries audit repository with descending timestamp ordering. 
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 20)
     * @param action  (optional)
     * @param entityType  (optional)
     * @param tenantId  (optional)
     * @param actor  (optional)
     * @param from  (optional)
     * @param to  (optional)
     * @return PageAuditLogResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platform audit logs returned </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not allowed by tenant/role/security policy </td><td>  -  </td></tr>
     </table>
     */
    public PageAuditLogResponse getPlatformAuditLogs(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String action, @javax.annotation.Nullable String entityType, @javax.annotation.Nullable String tenantId, @javax.annotation.Nullable String actor, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to) throws ApiException {
        ApiResponse<PageAuditLogResponse> localVarResp = getPlatformAuditLogsWithHttpInfo(page, size, action, entityType, tenantId, actor, from, to);
        return localVarResp.getData();
    }

    /**
     * Query platform-wide audit logs (SUPER_ADMIN)
     * Why this endpoint is needed: Super-admin operations require cross-tenant traceability for investigations and compliance.  What this endpoint does: It returns paged audit logs across all tenants with optional filters for actor/action/entity/tenant.  How this endpoint does it: Controller applies optional filter predicates and queries audit repository with descending timestamp ordering. 
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 20)
     * @param action  (optional)
     * @param entityType  (optional)
     * @param tenantId  (optional)
     * @param actor  (optional)
     * @param from  (optional)
     * @param to  (optional)
     * @return ApiResponse&lt;PageAuditLogResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platform audit logs returned </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not allowed by tenant/role/security policy </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PageAuditLogResponse> getPlatformAuditLogsWithHttpInfo(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String action, @javax.annotation.Nullable String entityType, @javax.annotation.Nullable String tenantId, @javax.annotation.Nullable String actor, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to) throws ApiException {
        okhttp3.Call localVarCall = getPlatformAuditLogsValidateBeforeCall(page, size, action, entityType, tenantId, actor, from, to, null);
        Type localVarReturnType = new TypeToken<PageAuditLogResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Query platform-wide audit logs (SUPER_ADMIN) (asynchronously)
     * Why this endpoint is needed: Super-admin operations require cross-tenant traceability for investigations and compliance.  What this endpoint does: It returns paged audit logs across all tenants with optional filters for actor/action/entity/tenant.  How this endpoint does it: Controller applies optional filter predicates and queries audit repository with descending timestamp ordering. 
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 20)
     * @param action  (optional)
     * @param entityType  (optional)
     * @param tenantId  (optional)
     * @param actor  (optional)
     * @param from  (optional)
     * @param to  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Platform audit logs returned </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not allowed by tenant/role/security policy </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPlatformAuditLogsAsync(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String action, @javax.annotation.Nullable String entityType, @javax.annotation.Nullable String tenantId, @javax.annotation.Nullable String actor, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, final ApiCallback<PageAuditLogResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPlatformAuditLogsValidateBeforeCall(page, size, action, entityType, tenantId, actor, from, to, _callback);
        Type localVarReturnType = new TypeToken<PageAuditLogResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getTenantAuditLogs
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 20)
     * @param action  (optional)
     * @param entityType  (optional)
     * @param from  (optional)
     * @param to  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Tenant audit logs returned </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getTenantAuditLogsCall(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String action, @javax.annotation.Nullable String entityType, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/audit-logs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (size != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("size", size));
        }

        if (action != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("action", action));
        }

        if (entityType != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("entityType", entityType));
        }

        if (from != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("from", from));
        }

        if (to != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("to", to));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getTenantAuditLogsValidateBeforeCall(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String action, @javax.annotation.Nullable String entityType, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, final ApiCallback _callback) throws ApiException {
        return getTenantAuditLogsCall(page, size, action, entityType, from, to, _callback);

    }

    /**
     * Query tenant-scoped activity logs
     * Why this endpoint is needed: Tenant operators need visibility into operational activity for troubleshooting and governance.  What this endpoint does: It returns paged audit logs filtered to the current tenant context.  How this endpoint does it: Controller derives tenant id from security context and applies optional filter parameters on audit-log repository. 
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 20)
     * @param action  (optional)
     * @param entityType  (optional)
     * @param from  (optional)
     * @param to  (optional)
     * @return PageAuditLogResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Tenant audit logs returned </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
     </table>
     */
    public PageAuditLogResponse getTenantAuditLogs(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String action, @javax.annotation.Nullable String entityType, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to) throws ApiException {
        ApiResponse<PageAuditLogResponse> localVarResp = getTenantAuditLogsWithHttpInfo(page, size, action, entityType, from, to);
        return localVarResp.getData();
    }

    /**
     * Query tenant-scoped activity logs
     * Why this endpoint is needed: Tenant operators need visibility into operational activity for troubleshooting and governance.  What this endpoint does: It returns paged audit logs filtered to the current tenant context.  How this endpoint does it: Controller derives tenant id from security context and applies optional filter parameters on audit-log repository. 
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 20)
     * @param action  (optional)
     * @param entityType  (optional)
     * @param from  (optional)
     * @param to  (optional)
     * @return ApiResponse&lt;PageAuditLogResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Tenant audit logs returned </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PageAuditLogResponse> getTenantAuditLogsWithHttpInfo(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String action, @javax.annotation.Nullable String entityType, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to) throws ApiException {
        okhttp3.Call localVarCall = getTenantAuditLogsValidateBeforeCall(page, size, action, entityType, from, to, null);
        Type localVarReturnType = new TypeToken<PageAuditLogResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Query tenant-scoped activity logs (asynchronously)
     * Why this endpoint is needed: Tenant operators need visibility into operational activity for troubleshooting and governance.  What this endpoint does: It returns paged audit logs filtered to the current tenant context.  How this endpoint does it: Controller derives tenant id from security context and applies optional filter parameters on audit-log repository. 
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 20)
     * @param action  (optional)
     * @param entityType  (optional)
     * @param from  (optional)
     * @param to  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Tenant audit logs returned </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication missing or invalid </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getTenantAuditLogsAsync(@javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String action, @javax.annotation.Nullable String entityType, @javax.annotation.Nullable OffsetDateTime from, @javax.annotation.Nullable OffsetDateTime to, final ApiCallback<PageAuditLogResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getTenantAuditLogsValidateBeforeCall(page, size, action, entityType, from, to, _callback);
        Type localVarReturnType = new TypeToken<PageAuditLogResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
