/*
 * Survey Engine MVP API
 * Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/_*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.OidcCallbackResponse;
import org.openapitools.client.model.OidcStartRequest;
import org.openapitools.client.model.OidcStartResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OidcRespondentFlowApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OidcRespondentFlowApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OidcRespondentFlowApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for completeRespondentOidc
     * @param state  (required)
     * @param code  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Callback processed and access code returned </td><td>  -  </td></tr>
        <tr><td> 302 </td><td> Redirect response emitted when returnPath was provided </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not allowed by tenant/role/security policy </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call completeRespondentOidcCall(@javax.annotation.Nonnull String state, @javax.annotation.Nonnull String code, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/auth/respondent/oidc/callback";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (state != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("state", state));
        }

        if (code != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("code", code));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call completeRespondentOidcValidateBeforeCall(@javax.annotation.Nonnull String state, @javax.annotation.Nonnull String code, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'state' is set
        if (state == null) {
            throw new ApiException("Missing the required parameter 'state' when calling completeRespondentOidc(Async)");
        }

        // verify the required parameter 'code' is set
        if (code == null) {
            throw new ApiException("Missing the required parameter 'code' when calling completeRespondentOidc(Async)");
        }

        return completeRespondentOidcCall(state, code, _callback);

    }

    /**
     * Complete OIDC callback and issue one-time responder access code
     * Why this endpoint is needed: Authorization-code OIDC requires callback handling to exchange code, verify trust, and convert external auth into internal responder access state.  What this endpoint does: It validates callback state/code, exchanges token at IdP, validates token claims, and issues one-time responder access code.  How this endpoint does it: OIDC state record is checked for expiry and one-time use, token exchange is executed via configured metadata, token validation service verifies claims/mappings, responder access code row is persisted, and either JSON response or redirect response is returned. 
     * @param state  (required)
     * @param code  (required)
     * @return OidcCallbackResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Callback processed and access code returned </td><td>  -  </td></tr>
        <tr><td> 302 </td><td> Redirect response emitted when returnPath was provided </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not allowed by tenant/role/security policy </td><td>  -  </td></tr>
     </table>
     */
    public OidcCallbackResponse completeRespondentOidc(@javax.annotation.Nonnull String state, @javax.annotation.Nonnull String code) throws ApiException {
        ApiResponse<OidcCallbackResponse> localVarResp = completeRespondentOidcWithHttpInfo(state, code);
        return localVarResp.getData();
    }

    /**
     * Complete OIDC callback and issue one-time responder access code
     * Why this endpoint is needed: Authorization-code OIDC requires callback handling to exchange code, verify trust, and convert external auth into internal responder access state.  What this endpoint does: It validates callback state/code, exchanges token at IdP, validates token claims, and issues one-time responder access code.  How this endpoint does it: OIDC state record is checked for expiry and one-time use, token exchange is executed via configured metadata, token validation service verifies claims/mappings, responder access code row is persisted, and either JSON response or redirect response is returned. 
     * @param state  (required)
     * @param code  (required)
     * @return ApiResponse&lt;OidcCallbackResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Callback processed and access code returned </td><td>  -  </td></tr>
        <tr><td> 302 </td><td> Redirect response emitted when returnPath was provided </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not allowed by tenant/role/security policy </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OidcCallbackResponse> completeRespondentOidcWithHttpInfo(@javax.annotation.Nonnull String state, @javax.annotation.Nonnull String code) throws ApiException {
        okhttp3.Call localVarCall = completeRespondentOidcValidateBeforeCall(state, code, null);
        Type localVarReturnType = new TypeToken<OidcCallbackResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Complete OIDC callback and issue one-time responder access code (asynchronously)
     * Why this endpoint is needed: Authorization-code OIDC requires callback handling to exchange code, verify trust, and convert external auth into internal responder access state.  What this endpoint does: It validates callback state/code, exchanges token at IdP, validates token claims, and issues one-time responder access code.  How this endpoint does it: OIDC state record is checked for expiry and one-time use, token exchange is executed via configured metadata, token validation service verifies claims/mappings, responder access code row is persisted, and either JSON response or redirect response is returned. 
     * @param state  (required)
     * @param code  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Callback processed and access code returned </td><td>  -  </td></tr>
        <tr><td> 302 </td><td> Redirect response emitted when returnPath was provided </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not allowed by tenant/role/security policy </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call completeRespondentOidcAsync(@javax.annotation.Nonnull String state, @javax.annotation.Nonnull String code, final ApiCallback<OidcCallbackResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = completeRespondentOidcValidateBeforeCall(state, code, _callback);
        Type localVarReturnType = new TypeToken<OidcCallbackResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for startRespondentOidc
     * @param oidcStartRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OIDC authorization URL generated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not allowed by tenant/role/security policy </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Referenced resource does not exist or is not visible in tenant scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call startRespondentOidcCall(@javax.annotation.Nonnull OidcStartRequest oidcStartRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = oidcStartRequest;

        // create path and map variables
        String localVarPath = "/api/v1/auth/respondent/oidc/start";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call startRespondentOidcValidateBeforeCall(@javax.annotation.Nonnull OidcStartRequest oidcStartRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'oidcStartRequest' is set
        if (oidcStartRequest == null) {
            throw new ApiException("Missing the required parameter 'oidcStartRequest' when calling startRespondentOidc(Async)");
        }

        return startRespondentOidcCall(oidcStartRequest, _callback);

    }

    /**
     * Start private responder OIDC flow
     * Why this endpoint is needed: Private campaigns need a secure and tenant-aware way to initiate responder SSO without exposing platform-internal logic.  What this endpoint does: It validates campaign + tenant eligibility for OIDC flow, creates one-time state/nonce context, and returns IdP authorization URL details.  How this endpoint does it: The OIDC service checks campaign auth mode and tenant auth profile mode, fetches OIDC metadata, stores state with expiry, composes authorization URL with scopes/state/nonce, and returns OidcStartResponse. 
     * @param oidcStartRequest  (required)
     * @return OidcStartResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OIDC authorization URL generated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not allowed by tenant/role/security policy </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Referenced resource does not exist or is not visible in tenant scope </td><td>  -  </td></tr>
     </table>
     */
    public OidcStartResponse startRespondentOidc(@javax.annotation.Nonnull OidcStartRequest oidcStartRequest) throws ApiException {
        ApiResponse<OidcStartResponse> localVarResp = startRespondentOidcWithHttpInfo(oidcStartRequest);
        return localVarResp.getData();
    }

    /**
     * Start private responder OIDC flow
     * Why this endpoint is needed: Private campaigns need a secure and tenant-aware way to initiate responder SSO without exposing platform-internal logic.  What this endpoint does: It validates campaign + tenant eligibility for OIDC flow, creates one-time state/nonce context, and returns IdP authorization URL details.  How this endpoint does it: The OIDC service checks campaign auth mode and tenant auth profile mode, fetches OIDC metadata, stores state with expiry, composes authorization URL with scopes/state/nonce, and returns OidcStartResponse. 
     * @param oidcStartRequest  (required)
     * @return ApiResponse&lt;OidcStartResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OIDC authorization URL generated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not allowed by tenant/role/security policy </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Referenced resource does not exist or is not visible in tenant scope </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OidcStartResponse> startRespondentOidcWithHttpInfo(@javax.annotation.Nonnull OidcStartRequest oidcStartRequest) throws ApiException {
        okhttp3.Call localVarCall = startRespondentOidcValidateBeforeCall(oidcStartRequest, null);
        Type localVarReturnType = new TypeToken<OidcStartResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Start private responder OIDC flow (asynchronously)
     * Why this endpoint is needed: Private campaigns need a secure and tenant-aware way to initiate responder SSO without exposing platform-internal logic.  What this endpoint does: It validates campaign + tenant eligibility for OIDC flow, creates one-time state/nonce context, and returns IdP authorization URL details.  How this endpoint does it: The OIDC service checks campaign auth mode and tenant auth profile mode, fetches OIDC metadata, stores state with expiry, composes authorization URL with scopes/state/nonce, and returns OidcStartResponse. 
     * @param oidcStartRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OIDC authorization URL generated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Request validation failed or business rule validation failed </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Authenticated but not allowed by tenant/role/security policy </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Referenced resource does not exist or is not visible in tenant scope </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call startRespondentOidcAsync(@javax.annotation.Nonnull OidcStartRequest oidcStartRequest, final ApiCallback<OidcStartResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = startRespondentOidcValidateBeforeCall(oidcStartRequest, _callback);
        Type localVarReturnType = new TypeToken<OidcStartResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
