# coding: utf-8

"""
    Survey Engine MVP API

    Comprehensive API contract for the Survey Engine MVP.  This specification is written for product, implementation, and integration teams. Every endpoint description intentionally includes: 1) why the endpoint is needed, 2) what the endpoint does, 3) how the endpoint works inside the platform lifecycle.  Security model summary: - Admin APIs accept engine-issued JWT via HttpOnly access_token cookie (primary) or Bearer header (fallback). - Headless clients can use explicit token-mode auth endpoints under /api/v1/admin/auth/token/*. - Admin sessions are maintained with refresh-token cookie rotation. - Browser cookie mode exposes CSRF bootstrap endpoint at /api/v1/admin/auth/csrf. - Responder submission endpoint is public at transport level, but private campaigns enforce tenant-scoped responder authentication in business logic. 

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class UpdateFeatureRequest(BaseModel):
    """
    UpdateFeatureRequest
    """ # noqa: E501
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    description: Optional[StrictStr] = None
    enabled: Optional[StrictBool] = None
    rollout_percentage: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=None, alias="rolloutPercentage")
    min_plan: Optional[StrictStr] = Field(default=None, alias="minPlan")
    roles: Optional[List[StrictStr]] = None
    platforms: Optional[List[StrictStr]] = None
    metadata: Optional[Dict[str, Any]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "description", "enabled", "rolloutPercentage", "minPlan", "roles", "platforms", "metadata"]

    @field_validator('min_plan')
    def min_plan_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['BASIC', 'PRO', 'ENTERPRISE']):
            raise ValueError("must be one of enum values ('BASIC', 'PRO', 'ENTERPRISE')")
        return value

    @field_validator('roles')
    def roles_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['SUPER_ADMIN', 'ADMIN', 'EDITOR', 'VIEWER']):
                raise ValueError("each list item must be one of ('SUPER_ADMIN', 'ADMIN', 'EDITOR', 'VIEWER')")
        return value

    @field_validator('platforms')
    def platforms_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['WEB', 'MOBILE', 'DESKTOP']):
                raise ValueError("each list item must be one of ('WEB', 'MOBILE', 'DESKTOP')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateFeatureRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateFeatureRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "enabled": obj.get("enabled"),
            "rolloutPercentage": obj.get("rolloutPercentage"),
            "minPlan": obj.get("minPlan"),
            "roles": obj.get("roles"),
            "platforms": obj.get("platforms"),
            "metadata": obj.get("metadata")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


